/**
 * NÁVOD: MAPA PORTÁLU (zadání 18. 9. 2026: „udělej mi přehled (mapu) celého
 * portálu, jakou má strukturu a jak obecně funguje. Aby to pochopil každý.
 * A dej to pak do nápovědy na portál rovnou").
 *
 * Je to úvodní návod pro každého, kdo portál otevře poprvé - proto pořadí 1
 * a kategorie „Začínáme". Schválně bez technických pojmů: kde co je, kdo co
 * vidí a co portál dělá sám.
 *
 * Text tady je jen ZAČÁTEK. Jakmile ho někdo v portálu upraví, seed už do něj
 * nesahá - zakládá se jen tehdy, když návod s touhle adresou ještě není.
 */
export const MAPA_PORTALU = {
  slug: 'mapa-portalu',
  nazev: 'Mapa portálu: co kde je a jak to funguje',
  perex: 'Celá cesta zakázky na jednom obrázku — klient, my a herec krok po kroku. K tomu mapa sekcí, kdo co vidí a co portál dělá sám.',
  kategorie: 'Začínáme',
  poradi: 1,
  obsah: `MS Portal drží celou zakázku na jednom místě: objednávku, projekt, natáčení, nahrávky pro klienta, smlouvu s hercem, fakturu i to, jestli přišla platba. Dřív to bylo rozseté mezi Caflou, e-maily, Disk a tabulky. Tenhle návod je mapa — kde co je, kdo co vidí a co se děje samo.

# Celá cesta zakázky na jednom obrázku

Vodorovně jde čas, od objednávky po zaplacenou fakturu. Ve třech pruzích je vidět, **co v které chvíli dělá klient, co my v portálu a co herec** — a u každého kroku i to, jestli se k tomu ten člověk přihlašuje, nebo mu stačí odkaz z e-mailu.

![Celá cesta zakázky: klient, Mediaspace a herec v šesti krocích](/navody/cela-cesta.png)

Tři věci, které z obrázku stojí za zdůraznění:

- **Klient ani herec nic neinstalují.** Schválení nabídky, podpis smlouvy, stažení nahrávek, přeposlech, výběr termínů i vyplnění údajů — všechno jde odkazem z mailu, který funguje sám o sobě. Účet v portálu je bonus, ne podmínka.
- **Prázdné místo v pruhu znamená, že ten člověk nemá co dělat.** Herec neřeší nabídku, klient neřeší plánování studia. Každý vidí jen svůj kousek.
- **Zelené pruhy dole jsou práce, kterou nikdo nedělá** — portál je udělá sám.

# Mapa sekcí

![Mapa portálu](/navody/mapa-portalu.png)

# Šest sekcí v horní liště

**Projekty** jsou srdce portálu. Každá zakázka má svou kartu: stav, termíny, herce, rozpočet, nahrávky, doklady. Většina práce se odehraje tady. V přehledu se řadí kliknutím na hlavičku sloupce; **stav se neřadí abecedně**, ale v pořadí, které si tým nastaví tlačítkem **Pořadí stavů** vedle hledání (přetažením nebo šipkami, mění ho Žůžo-labůžo a produkce, platí pro všechny). Nabídky stavů u projektu se to netýká — cesta projektu zůstává, jak je. Při **zakládání projektu** se datum ptá podle typu (8. 10. 2026): u reklamy je to **Datum dokončení** — náš termín —, u ostatních **Datum vydání**, tedy termín klienta. Dřív se vždycky ukládalo datum vydání, což u reklamy padalo do kolonky, která se na kartě projektu ani nenabízí, takže se datum ztratilo.

Na kartě klientské firmy je kromě Údajů, Notifikací a Účtů i záložka **Zakázky**: tabulka všech zakázek té firmy, kde jde ke každé doplnit **herce, nabídku a fakturu** a uložit to jedním tlačítkem — **potichu**, bez notifikací a bez zápisu do historie projektu. V nabídce dokladů jsou jen nabídky a faktury té firmy, které ještě žádnou zakázku nemají. Kontakt (klienta) ke všem zakázkám firmy najednou přiřadí tlačítko na záložce Přihlašovací účty, taky potichu.

U reklamy je cesta projektu krátká: nabízí se jen **V přípravě, Plánujeme, Natáčíme, Dokončeno - ke schválení a Schváleno - k fakturaci**. Audioknižní stavy — **Natáčíme/stříháme, Dotočeno, Dotočeno/stříháme, Čekáme na opravy a Opravujeme** — se u reklamy ani nenabízejí, ani se do nich nic nepřeklopí samo: odpočet „za sedm dní se překlopí na Čekáme na opravy" u ní neběží a tlačítko Dotočeno u herce jí stav nemění. Že je projekt reklama, se pozná z typu zakázky, ne z firmy: spot s Rodným listem je reklama vždycky, u firmy, která dělá jen reklamy, je reklama každá zakázka, a u firmy, která dělá obojí, je reklamou všechno kromě audioknihy. Zakázka bez vyplněného typu u takové firmy zůstává audioknihou — má delší cestu a dá se z ní ručně odbočit.

Klientovi reklamy se stavy ukazují jeho řečí: **V přípravě, Plánujeme, Natáčíme**, pak **Ke schválení** (u nás „Dokončeno - ke schválení") a od „Schváleno - k fakturaci" dál už jen **Dokončeno** — fakturace ani opravy do jeho přehledu nepatří. Klient, který u nás dělá **jen reklamy**, má v Projektech **vlastní přehled**: název, stav, herec, typ projektu, licence, datum dokončení, **Otevřít složku** (vede do našeho obrandovaného Disku, ne na Google) a tlačítko **Připomínkovat** (vede do taggeru spotu, kde píše připomínky a spot schvaluje; u dokončené zakázky už se nenabízí). **Dokončené zakázky jsou vidět rovnou**, klient si je může schovat tlačítkem. Klepnutím na licenci vyskočí u pilulky okno s **dokumenty ke stažení** (zavře se Escapem, klepnutím mimo nebo posunem stránky, jako náhled dokladů) — u každého tlačítko Stáhnout a nahoře **Stáhnout vše** v jednom archivu — rodný list u rádiového spotu, u ostatních reklam **všechny licenční listy zakázky** (jeden za každý výstup, pojmenované názvem spotu). Licenční listy se na Disk neukládají; klient je má v portálu. Normostrany se mu neukazují, u reklamy nedávají smysl; firma, která dělá i audioknihy, má přehled jako dosud.

Vedle názvu zakázky svítí dvě malé značky s tím, **jaké doklady u ní visí**: cenovka je nabídka (šedá rozepsaná, oranžová odeslaná, zelená schválená, červená odmítnutá), lístek je faktura (oranžová vystavená a nezaplacená, zelená uhrazená). Co u zakázky není, nesvítí; čísla dokladů jsou v bublince. **Klepnutí na ikonu ukáže náhled** (okno vyskočí hned u ní a zavře se dalším klepnutím kamkoliv do něj) — u nabídky a faktury odběratele, částku s DPH, vystavení, splatnost a stav (po splatnosti svítí červeně), u sluchátek kolik stop je poslechnutých, kolik je zápisů chyb a kdy se na tom naposledy pracovalo. V okně je tlačítko **Otevřít**, které pustí celý doklad nebo přeposlech v novém panelu, ať o přehled nepřijdete. Vidí to jen ten, kdo má na kartě zaškrtnuté **Vidí Banku** — stejná dvojice, co vidí peníze.

**Firmy** jsou klienti a dodavatelé. U klienta se kromě adresy a fakturačních údajů nastavuje i to, **které zprávy mu portál posílá** — na kartě firmy je záložka Notifikace a co tam není zapnuté, se neodešle. Nová firma má vypnuté všechno.

**Uživatelé** jsou lidé. Kromě role se u účtu zaškrtává, co ten člověk smí a co mu chodí: jestli může být manažerem projektu, jestli podepisuje smlouvy za Mediaspace, jestli vidí sekci Banka, jestli spravuje technické parametry, komu chodí objednávky. Je to schválně **u účtu, ne v kódu** — lidi se mění a portál o tom jinak neví.

U **zvukaře** se navíc zaškrtává **Studia** — ve kterých studiích točí. Kdo jezdí do Brna I i Brna II, má zaškrtnutá obě. Projeví se to na dvou místech: v seznamu uživatelů je to vidět ve sloupci Lokace a v kalendáři jde k události vybrat **jen zvukaře z toho studia** — na brněnskou frekvenci pražského nezapíšete, a naopak. Hlídá to i server, ne jen nabídka ve formuláři. Dokud u nikoho v daném studiu není nic zaškrtnuté, nabízejí se všichni, ať jde frekvence zapsat; kdo je u starší události napsaný, v ní zůstane. Zaškrtávátka jsou ze skutečných studií, takže nově založené studio v nabídce přibude samo.

Kdo má jinou roli (třeba Žůžo-labůžo) a občas dělá i zvukaře, má na kartě zaškrtnuté **Může být i zvukař**. Role mu zůstane, jen se navíc nabízí mezi zvukaři u natáčení a střihu v kalendáři. Když nemá zaškrtnutá žádná studia, nabízí se ve všech. Takhle je nastavený Peter Dratva.

**Dva herci téhož jména** se v portálu rozliší městem (9. 10. 2026): v bublinách a v nabídkách stojí „Ondřej Novák - Brno“ a „Ondřej Novák - Praha“. **Jméno na kartě herce se nemění** — kdyby se město dopsalo tam, vytisklo by se i na smlouvu, honorář a rodný list, kam nepatří. Rozlišení se dopočítává při vykreslení z **lokací na kartě herce**, takže platí i **zpětně** na staré projekty a nic se v datech nepřepisuje. Přidává se jen u jmen, která nosí víc lidí; kdyby měli oba stejné město (nebo žádné), vezme se místo něj kód z karty. Názvy projektů portál drží **velkými písmeny** — ať už je někdo zadá jakkoli, uloží se velkými a stejně se jmenuje i kanál projektu v chatu. Přejmenování projektu přepíše i název kanálu. V chatu se na projekt odkazuje **mřížkou** — napíše se # a začátek názvu. Nabídka si od 8. 10. 2026 **seznam projektů sama osvěží** (nejvýš jednou za půlminutu); do té doby se stáhl jen při otevření záložky Projekty, takže čerstvě založený projekt pod mřížkou nebyl k nalezení, i když jeho kanál už v seznamu nalevo byl.

**Kanál projektu v chatu zmizí ze seznamu, až je projekt vyfakturovaný** — ne dřív. Ve stavech jako *Dotočeno* nebo *Dokončeno - ke schválení* se na projektu pořád dělá, takže kanál zůstává (do 6. 10. 2026 mizel už tam a kliknutí na něj v záložce Projekty skončilo na prázdném okně). Zprávy se nikdy nemažou, jen se kanál schová; když se projekt vrátí mezi rozpracované, vrátí se i kanál. Totéž platí pro **kanál dotazů klienta** — ten se zavírá ve stejnou chvíli, ne při odevzdání k poslechu, kdy má klient otázek nejvíc.

**Wikipedie** (Administrace → Wikipedie) je místo, kde si článek o sobě na Wikipedii napíšete a vyladíte: vlevo wikitext, vpravo náhled, jak ho vykreslí Wikipedie, a uložené verze, ke kterým se jde vrátit. Portál na Wikipedii nic neukládá. Text zkopírujete a vložíte tam sami svým účtem, návod je přímo na stránce. Až bude článek venku, napište jeho název do Hlídání a portál vám každou hodinu zvonkem ohlásí, když ho někdo upraví. Každý tu vidí jen svůj článek. V záložce **Údaje o sobě** se vyplní jméno, datum a místo narození, povolání, fotka z Commons, zdroje, milníky a tvorba; tlačítko **Sestavit text z údajů** z toho poskládá hotový wikitext včetně referencí. V záložce **Vzpomínání** si můžete povídat s pomocníkem: vyprávíte, co jste zažili, on se doptá na podrobnosti a na zdroje a napíše hotový kus wikitextu, který se jedním kliknutím přidá do konceptu. Text jde z portálu i **rovnou odeslat na Wikipedii** — stačí jednou vložit osobní přístupový token (OAuth „owner-only" z meta.wikimedia.org) a vyplnit, kam se má uložit; odesílá se poslední uložená verze a úprava jde pod vaším účtem.

**Ceníky** jsou dvě věci najednou: ceny služeb a zároveň seznam typů projektu. U projektu jde vybrat jen takový typ, který je v ceníku — proto se nové typy přidávají tady.

**Doklady** jsou peníze: nabídky, faktury, upomínky, přijaté výdaje, smlouvy, banka a „Moje firmy" (za kterou firmu doklad vystavujeme, číselné řady, bankovní účty, podpis na faktury). U výdaje se nahraje PDF nebo fotka dokladu (i víc souborů) — údaje se z něj přečtou samy; přílohy i údaje jde kdykoli později doplnit v detailu výdaje. Co se platí **na vícekrát** (smlouva, velká faktura), se v detailu výdaje zapisuje po částech — karta **Úhrady**: kolik odešlo a kdy. Portál z toho drží **kolik je uhrazeno a kolik zbývá doplatit**, v seznamu svítí odznak „Částečně" a QR platba se kreslí už jen na zbytek. Uhrazeno se doklad označí sám, jakmile se částka dorovná.

- **Kalendář splatností** (7. 10. 2026) — v **Neuhrazených** fakturách je přepínač *Tabulka / Kalendář splatností*. Kalendář kreslí týdny pod sebou, v každém dni jsou jen částky; když na jeden den padnou aspoň dvě faktury, přibude pod nimi součet dne, a u každého týdne je součet týdne. Měny se nesčítají dohromady, stojí vedle sebe. Částky jsou obarvené podle toho, jak to hoří: **červená** už měla být dávno zaplacená, **fialová** je na dnešek, **oranžová** přijde do týdne, **zelená** má čas — legenda je nad kalendářem. Dnešní den má fialový rámeček i štítek *dnes* a týden, ve kterém právě jsme, má fialový okraj; součet týdne zbarví do červené, když je v něm něco po splatnosti. Faktury bez vyplněné splatnosti jsou v pruhu pod kalendářem. **Najeěte myší na částku** a ukáže se, o kterou fakturu jde — číslo, odběratel, předmět, projekt a splatnost; kliknutí otevře samotnou fakturu. **Přepínač vidí jen superadmin** — ostatním se nevykreslí a kalendář nemají jak otevřít. (Čísla sama tajná nejsou: tytéž částky i splatnosti stojí v tabulce, kterou v Dokladech vidí celé Žůžo-labůžo.)

Když herec po podepsané smlouvě pošle ještě **fakturu** (typicky plátce DPH — na smlouvě je částka bez daně), nezakládá se druhý náklad. U výdaje ze smlouvy je karta **Faktura ke smlouvě**: buď se vybere doklad, který už v portálu leží mezi nezařazenými, nebo se faktura rovnou nahraje. Doklad pak má dvě přílohy (smlouvu i fakturu), v přehledech se počítá **jednou** a částka i QR platba jsou podle faktury, tedy **s DPH**.

Na záložce **Upomínky** se nastavuje, co se děje s fakturou, kterou klient nezaplatil včas. Upomínají se jen faktury **odeslané, nezaplacené a po splatnosti** — koncept ani uhrazená faktura nikdy. Nastavuje se, kolikátý den po splatnosti upomínka odejde (výchozí třetí, desátý a jednadvacátý den, tedy tři upomínky — kolik čísel, tolik upomínek), předmět a text (do textu jdou proměnné jako {cislo}, {castka}, {splatnost}, {dnu}) a komu má chodit skrytá kopie. Pod tím je **náhled e-mailu** přesně tak, jak ho klient uvidí, a seznam faktur po splatnosti s tlačítkem **Poslat upomínku** — to nečeká na ranní úlohu a pošle hned. Dokud není automatické posílání zapnuté, odcházejí upomínky jen tímhle tlačítkem. Píše se tomu, komu šla faktura: kontaktu firmy, a když ho firma nemá, klientovi projektu.

**Kalendář** má vedle studií ještě tři samostatné kalendáře: **Mimo studio** (kdo není), **Porady** (žluté) a **Schůzky** (tyrkysové) — **obojí jen pro účastníky** (8. 10. 2026): kdo u události není zapsaný, nevidí ji v kalendáři, nedostane ji do ranního přehledu ani připomínku 15 minut předem (do 8. 10. viděla produkce a admini všechny schůzky a chodila jim upozornění i na cizí). Založit, změnit nebo zrušit schůzku dál smí jen produkce — a jen tu, u které je. Jinak je to studio a natáčení: kdo kdy natáčí, kdy je studio blokované a nabídky termínů pro herce. Události zapisuje a upravuje produkce a vedoucí pobočky ve svých studiích (zaškrtává se na kartě uživatele – Tomáš Ilavský Brno, Ondřej Černý ml. Praha); ostatní si zapisují Mimo studio. Tlačítko „+ Přidat“ vedle přepínače Den/Týden/Měsíc otevře zápis i bez dvojkliku. V okně **Nová událost** je nahoře vedle křížku **ikona týdne** — přepne okno do **módu plánování** (8. 10. 2026): pod časem se objeví řádek Po–Ne, zaklikneš další dny a tlačítko se změní na „Přidat do kalendáře (3)“. **Týdny se rolují stejně jako kalendář** (8. 10. 2026) — řádek je pás tří týdnů vedle sebe, takže ho prst táhne přímo, **dva prsty na touchpadu** přes něj překlápějí týden po týdnu (stačí i směrem nahoru dolů) a na počítači jsou nad ním ještě šipky ‹ ›. Vybírat se dá i napříč týdny; co je zaškrtnuté jinde, než právě vidíš, se vypisuje pod pásem jako „Vybráno: …“. Druh, studio, projekt, herec, zvukař i poznámka se vyplní **jednou pro všechny** — nemusí se pokaždé vyklikávat zvukař ani studio; čas je u všech dnů stejný a jednotlivé se doladí tažením přímo v kalendáři. Dny se zapisují po jednom, a když se některý kryje s tím, co už v kalendáři stojí, portál řekne který — „Uložit i tak“ pak dopíše už jen ty. Při úpravě existující události se ikona nenabízí. Ikonka se čtyřmi rohy vedle šipek přepne kalendář na **celou obrazovku** (zpátky Escapem nebo druhým klepnutím). Vedle nadpisu Kalendář jsou dvě ikony: **výstražný trojúhelník** s počtem konfliktů (co se pere — vaše vlastní vidíte jen vy, z natáčení jen to, kde jste označení) a **hodiny se šipkou** s historií, kdo kdy co v kalendáři změnil. Konflikt, který je schválně, odklepnete v panelu tlačítkem **Je to záměr** — přestane svítit i v liště a dole v panelu zůstane, aby šel vrátit. Jakmile se některá z těch dvou událostí posune, upozornění se vrátí samo.

**Přehled dne a připomínky.** V Můj účet se dá zapnout **Hlídat mi den**: ráno v sedm přijde **upozornění do telefonu** a při prvním otevření portálu vyskočí **okno s programem dne**; patnáct minut před každou událostí navíc přijde **připomínka** od Bruna do chatu i do telefonu. V okně je, co vás ten den čeká — natáčení, střihy a castingy, kde jste zvukař nebo herec, porady, na které jste pozvaní, Schůzky (produkce je vidí všechny) a u koho chodí **režie na dálku** — každé s ikonou svého druhu a štítkem studia. Pod tím jsou **úkoly s dnešním termínem**; dlouhodobé sem nepatří, ty jsou v to-do listu. **Kouknout se jde kdykoliv během dne:** v levém panelu rychlých voleb je **Co mě dnes čeká** — jedno klepnutí a okno se otevře znovu (ráno pak vyskočí tak jako tak). **Co už proběhlo, v okně není** — odpovídá na „co mě ještě čeká", takže událost z něj zmizí, jakmile doopravdy skončí; rozjeté natáčení v něm zůstane až do konce. **Před první frekvencí s hercem** přidá Bruno pár vět o tom, **o čem ta kniha je** — přečte si režijní edit ve složce projektu a napíše, co se v knize děje, jakým tónem je psaná a která jména se špatně vyslovují. Píše to jen z rukopisu, nic si nedomýšlí; udělá se to jednou a pak to u projektu vidí každý. **Zeptat se jde i kdykoliv jindy:** napište Brunovi do chatu „Bruno, co mám dneska?“ (nebo zítra, v pátek, 30. 9.) a přehled pošle hned. **Bruna si jde v chatu založit jako kohokoliv jiného** — v nové zprávě je v seznamu lidí; v soukromé konverzaci s ním se oslovovat jménem nemusíte, mluvíte s ním tak jako tak. **Povídat si s ním jde normálně**: drží nit rozhovoru a zvládne i věci mimo portál — napsat nebo učesat text, přeložit, vymyslet názvy, něco vysvětlit. Do portálu si přitom sáhne sám, když je odpověď v datech.

Kromě toho je v liště ještě **chat**, **zvoneček** s upozorněními, **otazník** (tahle Nápověda) a vlevo panel s rychlými volbami. Vlevo nahoře je značka a ta má **dvě různá tlačítka** (6. 10. 2026): nápis **MS portal** vede domů na Projekty, **animované logo** načte znovu tu stránku, na které právě stojíte. Obojí sáhne na server, takže se tím vytáhne i nově nasazená verze — ve stažené aplikaci z Chromu, kde není adresní řádek ani tlačítko Znovu načíst, je to jediná cesta, jak portál obnovit myší.

**Kopírování z chatu** (připomínka Petera Dratvy 7. 10. 2026) — **myší se text v bublině označí táhnutím** jako kdekoli jinde a pravé tlačítko nad výběrem nabídne systémové *Kopírovat*; nabídka reakcí se otevře pravým tlačítkem jen tam, kde nic označeného není. **Na telefonu** zůstává podržení prstu pro reakce (jinak by iOS označoval celou stránku) — když je potřeba vzít jen kus textu, například zaslané heslo, je v té nabídce vedle *Kopírovat* (ta vezme celou zprávu) ještě **Vybrat text**, která na té jedné bublině pustí výběr prstem.

**Vlákna v chatu.** Na každou zprávu jde odpovědět ve vlákně - odkaz **Odpovědět** se u zpráv ukáže po najetí myší (v mobilu svítí pořád). Trvale visí jen u poslední zprávy ze série od jednoho člověka a u zpráv, pod kterými už nějaké odpovědi jsou, aby seznam nebyl samý odkaz. Vlákno se otevře vpravo a **roluje se rovnou na poslední odpověď**; upozornění na odpověď ve vlákně otevře to vlákno rovnou (do 6. 10. 2026 otevřelo jen rozhovor a nová zpráva v něm nebyla vidět, protože visí pod rodičovskou zprávou).

**Úkoly z chatu.** Zpráva začínající **@úkol** založí úkol tomu, komu píšete (ve skupině tomu, koho označíte @jménem). Co jste takhle zadali ostatním, najdete v panelu **Úkoly** (i v záložce Úkoly v chatu) dole v části **Zadal jsem**: pro koho, do kdy a jestli už je hotovo. Když ho příjemce odškrtne, přijde vám zpráva pod **zvoneček**; stejně tak, když nesplněný úkol smaže. Kliknutím na úkol se otevře konverzace, ze které vznikl. Tužkou ✎ vedle úkolu ho můžete **upravit** — název, datum i čas — nebo **zrušit**; tomu, komu patří, o tom přijde zpráva. Odškrtnout ho za něj nejde.

**Klient může přiložit soubor.** V Dotazech je u psátka sponka — klient přiloží **PDF** (scénář, korekturu, objednávku) nebo obrázek, nejvýš pět souborů po 15 MB. Nic jiného tudy neprojde; dotazy nejsou úložiště. Přílohu vidíme v MS chatu v tomtéž kanálu jako kteroukoliv jinou a otevře se jen přihlášenému, kdo do toho kanálu patří. Samotná příloha bez textu je taky dotaz — klient pošle scénář a napíše až potom.

**Dotazy klientů mají v chatu svou záložku.** Na horní liště chatu je vedle Projektů a Úkolů záložka **Dotazy klientů** s vlastní ikonou; nepřečtené na ní svítí **červeně**, ne zeleně jako u ostatních, a sam otevřený seznam má červený pruh. Kdykoli klient pošle dotaz, **přijde upozornění pod zvoneček a do telefonu** každému, kdo má na kartě zaškrtnuté „Dostává dotazy klientů“ — i když má zrovna tiše nebo si kanál ztišil. Dotaz klienta je jiná kategorie než bežná zpráva v chatu: nemá čekat do rána. Komu se právo přidá později, přibyde i do **už založených** kanálů dotazů, ne jen do nových.

**Klient se dozví o odpovědi.** Když klientovi odpovíme v jeho **Dotazech**, přijde mu mail, že má v portálu nepřečtenou zprávu — s ukázkou a odkazem, který dotaz rovnou otevře. Chodí **jeden mail na jedno nepřečtení**: další až potom, co si zprávy přečte, takže se při psaní tam a zpátky schránka nezahltí. Kdo je zrovna v portálu (četl v posledních patnácti minutách), mail nedostane vůbec.

**Status v chatu.** Nad seznamem rozhovorů je proužek **Nastavit status** — co zrovna děláte, uvidí ostatní u vašeho jména v chatu (v seznamu i v hlavičce otevřené zprávy). Je z čeho vybrat jedním klepnutím (Na obědě, Ve studiu, Na cestě…) nebo si napíšete vlastní i s emoji a nastavíte, jak dlouho platí. **Mimo studio se doplní samo** všem, kdo to mají zapsané v kalendáři Mimo studio. Komu je na kartě zaškrtnuté **Status v chatu z kalendáře**, tomu se sám nastaví i **„Mám schůzku do 14:30"** (porady a schůzky), **casting** na celou dobu a **režie na dálku** na prvních třicet minut — na zbytek frekvence už status nesvítí. **U zvukaře** se navíc samo ukáže, na čem zrovna dělá — ikona **natáčení**, **střihu** nebo **castingu** (tytéž kresby jako v kalendáři) a u ní **název projektu** a do kolika. Vlastní status má přednost, dokud platí; jakmile vyprší, vrátí se ten z kalendáře.

**Upravit jde i vlastní úkol.** Tužka ✎ u úkolu v panelu i v záložce Úkoly v chatu otevře název, datum i čas k přepsání — překlep ani posunutý termín se nemusí psát znovu. Ve stejném okénku je i mazání (na dvě klepnutí).

**Termín s časem.** U každého úkolu (vlastního, zadaného v chatu i v panelu) jde vedle data vyplnit i **čas, do kdy** má být hotový. Je dobrovolný — bez času platí úkol do konce dne. Po termínu se úkol obarví červeně hned, jak čas uplyne.

# Uvnitř projektu

Karta projektu má záložky a ukazují se jen ty, které dávají smysl:

- **Přehled** — nahoře Progres natáčení (celý projekt a pod ním každý herec), pak stav, termíny, klient, herci, odkaz pro klienta. Vidí ho každý. U knihy s víc herci platí, že **každý čte své rozházené kapitoly po celé knize** — nikdo nemá souvislý úsek. Procento je proto u všech stejná metrika: jak daleko jsme v textu. Normostrany herce jsou **váha a plánovací číslo**, ne pozice: z nich se počítá, kolik normostran mu ještě zbývá natočit (tedy kolik frekvencí mu naplánovat), a kolik váží na celkovém procentu projektu. Převod dělá **koeficient té knihy** (normostrany ÷ strany textu — každá kniha má jiný, počítá se pokaždé znovu). Když někomu rozsah chybí, portál to napíše a místo váženého součtu bere průměr.
- **Rozpočet** — položkové náklady, výkazy zvukařů, bonusy. Admin a produkce. Ve výkazech je vedle **Natáčení** a **Střihu** i druh práce **Opravy** (přetáčky a opravy už natočené knihy). Opravy se navazují na projekt stejně jako ostatní práce a **čerpají rozpočet na výrobu**, ale vlastní řádek v něm nemají — rozpočet se počítá z normostran a přetáčením normostran neubývá. V grafu Čerpání proto stojí jako třetí sloupec bez stropu a v celkovém rozpočtu se odečítají od zisku podle toho, co se opravdu vykázalo.
- **Přehledy → Kapacita studií** — měsíc na jedné obrazovce: řádek den, sloupec studio a v něm ranní a odpolední frekvence (9-13, 13-17 podle zkratek studia), každá jako obdélníček. Čím tmavší, tím víc **natáčení** proti otevírací době studia; prázdné místo je díra. Víkendy mají vlastní podklad, hodiny ukáže najetí myší, nad tabulkou je proužek dvanácti měsíců s procenty. Střih, casting ani blokace se nepočítají. Pod mřížkou jsou **grafy** (obsazenost po měsících, podle dne v týdnu, ranní vs. odpolední frekvence) a tlačítko **Stáhnout data (CSV)** pro vlastní analýzy v Excelu. Admin a produkce.
- **Přehledy → Obrat a zisk** (jen admin) — obrat z vydaných faktur, náklady z výdajů a zisk bez DPH v korunách: dlaždice se srovnáním s minulým obdobím, graf po měsících nebo čtvrtletích (najetím přesná čísla, jde přepnout na tabulku), obrat podle klientů, náklady podle kategorií a tabulka projektů. Nahoře výběr roku nebo posledních 12 měsíců, firmy a přepínač Vystaveno/Uhrazeno (podle data dokladu, nebo jen peníze, které opravdu přišly a odešly). V režimu **Uhrazeno** se výdaj placený na vícekrát počítá **po jednotlivých úhradách** ke dni, kdy peníze odešly — ne celý naráz. Pod grafem je karta **DPH**: daň na výstupu (z vydaných faktur), na vstupu (z výdajů, kterou si odečítáme) a **k odvedení** = rozdíl; záporné číslo je nadměrný odpočet, tedy peníze zpátky. Vedle je rozpad po měsících nebo čtvrtletích, podle toho se platí. Je to **ukazatel, ne přiznání** — portál nezná přenesenou daňovou povinnost, OSS ani krácený odpočet, a přiznání se podává podle data zdanitelného plnění, takže v režimu Uhrazeno je to číslo jen orientační. U neplátce nebo samých nulových sazeb se karta neukáže vůbec.
- **Přehledy → Bonusy** (u toho, kdo vidí jen svůj podíl, se záložka jmenuje **Moje bonusy**) — podíl na obratu. **Počítá se po měsících:** nahoře jsou vedle sebe **tento měsíc a ten minulý** (6. 10. 2026) — u každého bonus velkým písmem a pod ním drobně obrat, ze kterého vyšel; vedle podíl v procentech a roční součet jako doplněk. Prvního v měsíci je rozjetý měsíc skoro nula, takže teprve ten dokončený vedle něj dává smysl. V lednu je v minulém měsíci prosinec loňského roku. Pod tím je **graf po měsících** (rozjetý měsíc je vyšrafovaný, protože ještě poroste) a tabulka měsíc po měsíci; nad vším je **přepínač roku**, takže se dá podívat i na minulé roky. Základ: **vystavené faktury podle data vystavení, v korunách bez DPH** — tedy stejný obrat, jaký ukazuje Palubovka; stornované a rozpracované faktury se nepočítají. Procento se zadává na **kartě uživatele** (pole *Podíl na obratu*) a Žůžo-labůžo ho přepíše i dole v tabulce **Podíly celého týmu**, kde je u každého minulý měsíc, ten rozjetý a rok — uloží se po odkliknutí. Kdo nemá podíl vyplněný, tomu se záložka vůbec neukáže.
- **Přehledy → Zvukaři** (jen admin) — co za vybraný měsíc chodí zvukařům v měsíčním přehledu: hodiny, částka a bonusy každého, rozpad podle druhu práce a projektů, jestli a kdy mail odešel a náhled jeho mailu. Pod tím nastavení: vypínač, den rozeslání (1.–28., v 8:00 za měsíc minulý), co v mailu je (částky, druhy práce, projekty, bonusy) a vlastní vzkaz. Tlačítko „Rozeslat teď" pošle přehled těm, komu ještě neodešel.
- **Tabule ve studiích** — dotykový displej ve studiu: datum a čas, dnešní program studia z kalendáře (co právě probíhá, nebo dokdy je volno a co je další), poznámky (zůstávají, dokud je někdo neodškrtne) a dlaždice „co chybí“ (káva, toaletní papír, kapesníky…). Ťuknutí na chybějící věc pošle Báře Šiblové zprávu od Bruna. Zapíná se a adresa pro displej se bere v Administrace → Studia; displej se nepřihlašuje.
- **Rezervace studia klienty** — muzikanti a producenti, kteří si u nás bookují studio, mají vlastní kalendář na **/studio**: vidí volno, berou si termíny sami a rezervace platí hned. Svoje události vidí pojmenované, cizí (včetně našeho natáčení) jen jako obsazený čas bez názvů. Zapíná se u každého studia zvlášť v Administrace → Studia, tam se taky posílají pozvánky a odebírá přístup; totéž má pod kalendářem studia i **vedoucí pobočky** (panel Správa rezervací na /studio), takže kvůli pozvánce nemusí do administrace. Kdo nějaké studio s rezervacemi spravuje, má odkaz **Studio** rovnou v horní liště (stejně jako Tabuli) — a když si ho odtud smaže, zůstane smazaný. Rezervace se zapíše rovnou do kalendáře studia jako událost druhu **Rezervace studia**, takže se počítá do obsazenosti i konfliktů a dá se u ní stejně jako u jiné události poznamenat zvukař nebo ji přepsat na jiný druh práce. Návod pro klienty je anglicky, čtou ho na **/studio/napoveda**. Klient si pod svým jménem nastaví údaje a tři upozornění: potvrzení rezervace, změna nebo zrušení termínu z naší strany (posílá se, když s rezervací v kalendáři hneme nebo ji smažeme) a připomínka den předem.
- **Natáčecí plán** — plánování studia a herce a nad tím **Hosté na natáčení**. U některých natáčení bývá klient — ve studiu, nebo se připojuje na dálku. Termíny se sem berou **z kalendáře studia** (co je k projektu zapsané jako natáčení), nezakládají se tu; druhý seznam by se s kalendářem rozešel a hostům by chodily časy, které ve studiu neplatí. Každý host má **svůj řádek** — stačí e-mail a **jazyk** (rozbalovací seznam s vlaječkou — Čeština / Angličtina), na jméno se už neptáme; další řádek přibývá tlačítkem **+ Další host**, křížkem se mazá. **Jazyk je u každého zvlášť**, takže na jedno natáčení může odejít česká i anglická pozvánka — přeloží se celý mail, předmět, formát data i popis v kalendářové příloze (adresa zůstává česká — klient podle ní hledá místo; **parkování má u studia vlastní anglickou větu**, a když ji nikdo nevyplnil, pošle se česká). Už přidanýmu hostovi se dá **Upravit** adresa i překlepnout jazyk; po změně adresy se host vrátí mezi ty, kdo čekají na pozvánku — nová adresa žádnou nedostala. Adresa, která jako e-mail nevypadá, se obarví červeně a **Přidat** se dá zmáčknout, až když jsou všechny v pořádku. Když zkopírujete celý řádek z mailu („Jan Novák <jan@firma.cz>, petra@agentura.cz“) a vložíte ho, **rozhází se do řádků** (jména se zahodí) — je tak vidět a dá se opravit, než pozvánka odejde. **Ve studiu, nebo online se neurčuje** — většina klientů se dnes připojuje a stejně si to rozmyslí na poslední chvíli; pozvánka je pro oba případy táž a host si z ní vybere sám. Tlačítkem **Poslat pozvánky** jim odejde mail bez nadpisu a bez oslovování jménem — jedna věta a hned **přehled Projekt · Herec · Kde · Kdy · Parkování**, pod ním **Připojit se k natáčení online**, pak **Otevřít v mapách** a **Přidat do kalendáře**. Tlačítko do kalendáře vede na odkaz, který se skládá až při klepnutí — po přesunu termínu tedy i starý mail uloží **nový čas**. Tentýž záznam zůstává i v příloze mailu.

  **„Připojit se“ neveze klienta rovnou do hovoru, ale do naší čekárny** — obrandovaná stránka s **odpočtem do začátku** (vteřiny utíkají), projektem, hercem a časem a velkým tlačítkem do hovoru, které **zezelená přesně v čas začátku**. Adresa, parkování ani mapa tu nejsou — kdo je na téhle stránce, připojuje se na dálku a cestu má v pozvánce. Odkaz do hovoru je na stránce vidět i celý textem, kdyby tlačítko neotevřelo nové okno. Stránka se otevře bez přihlašování (chrání ji týž náhodný token jako Přidat do kalendáře) a je v jazyce hosta. Odkaz na videohovor se bere **od studia** a u konkrétního natáčení jde přepsat. Jedna podoba záměrně: klient si na poslední chvíli rozmyslí, že nepřijde osobně a připojí se, a všechno má v témže mailu. V přehledu je i řádek **Účastníci** — všichni pozvaní pod sebou a očíslovaní, ať je vidět, kolik jich bude. **Maily chodí každému zvlášť, ne v kopii**, takže odpovědi se vrací produkci a ne celé skupině — adresy ostatních ale host v tom seznamu uvidí, stejně jako by je viděl v kopii.

**Klientovi se říká čas o 15 minut později.** Když je natáčení v kalendáři od 11:30, v pozvánce i v kalendářové příloze stojí **11:45** — ta první čtvrthodina je na nachystání a zvukovou zkoušku s hercem. Dopočítá se to samo, nikde se nic nepřepíná a v kalendáři studia zůstává čas dohodnutý s hercem. V **detailu události v kalendáři** (dvojklik na ně) je pod hercem vidět **„Klient se připojí 11:45“** a pod tím jména a maily, na které pozvánka šla. Odejde jen těm, komu pozvánka ještě nešla — a taky tomu, komu se od jeho pozvánky **posunul termín** (u řádku to svítí a mail začne tím, že platí nový čas). Odpovědi chodí tomu, kdo pozvánku poslal. Odkaz na připojení se bere **od studia** a je u termínu **vypsaný a proklikatelný**, ať je vidět, co hostovi opravdu odejde; tlačítkem **Upravit** se u konkrétního natáčení přepíše (třeba když klient posílá svoji místnost) a uložením prázdného se zase vrátí studiový. Adresu, odkaz do map a parkování (česky i **anglicky**) se vyplňují u studia v Administrace → Studia.
- **Výstupy** — u reklam: seznam toho, co se pod projektem doopravdy vyrábí. Jeden výstup = jedna odevzdaná věc (spot, online voiceover, zkrácená verze) a celý se zadává **na jednom řádku**: název, kdo v něm mluví, délka a licence. Herci i licence se vybírají v malém okně u tlačítka, délka se píše v sekundách a od minuty výš v minutách (**30s**, **2min.**, **1min.30s**) — napsat jde 90, 1:30 i „1 min 30 s“, portál si to srovná. Režii, hudbu a datum výroby má projekt jednou v záložce Rodný list a dokument si je odtamtud vezme. Tečky na konci řádku nabídnou rodný list, zkrácenou verzi (ťukne se na délku a zbytek dědí po hlavním spotu) a smazání. **Rodný list se dělá u každého výstupu zvlášť** — rozhoduje typ výstupu, takže pod jedním projektem ho rádiový spot dostane a online voiceover ne. Co klient naklikal v objednávce, sem přijde jako **návrh** a uložením řádku ho produkce potvrdí. Tlačítko **Nabídka z výstupů** (jen kdo vidí doklady) založí rozpracovanou nabídku — jedna položka za výstup, ceny se doplní jen tam, kde je zná ceník. Projekt založený dřív si při prvním otevření udělá jeden výstup ze svých dosavadních údajů. U každého výstupu je tlačítko **Text**: rozklepne se pod řádkem a **text spotu** se do něj napíše, vloží ze schránky, nebo **nahraje z Wordu** (**.docx**, taky .txt a .md). Nahraný soubor se jen přečte — text se objeví v políčku, dá se ještě upravit a uloží se až tlačítkem **Uložit** u řádku, takže nahrání nikdy tiše nepřepíše, co tam bylo. Tlačítko svítí fialově u výstupů, které už text mají, takže je v sadě čtyř délek vidět, kde chybí. Zkrácená verze má text vlastní — po hlavním spotu ho nedědí, protože je kratší. Tlačítko **Natáčecí text na Disk** vyrobí ve složce projektu **editovatelný dokument**: jeden za projekt, spoty pod sebou, u každého název, délka a licence a pod tím text spotu, jak je napsaný u výstupu (kde ještě není, zůstane volné místo). Do hotového dokumentu portál nesahá — dopisuje se v něm na Disku a každé další kliknutí udělá nový soubor. Podobu listu si tým píše v Administraci → **Vzory natáčecích textů** (úvod dokumentu a blok spotu, s proměnnými). Název se řídí stopáží a licencí: jakmile se vyplní délka, doplní se do něj sám (**STRABAG - 2min._online**) a při změně se přepíše — do ručně psané části portál nesahá. Vpravo vedle řádků je **náhled** toho listu — celá **A4** naráz, bez posouvání, přesně tak, jak bude vypadat na Disku: fialová hlavička se zeleným logem a názvem projektu (**jméno klienta v listu není** — list vidí herci i studio a zadavatel do něj nepatří), pod ní datum poslední úpravy výstupů (ne dnešek — to by se četlo jako den natáčení) a spoty pod sebou bez číslování.
**Doklady u zakázky** (1. 10. 2026). V klientském přehledu je sloupec **Doklady** s ikonami: cenovka = nabídka, list s řádky = faktura, list s odškrtnutými řádky = objednávka z webu. Barva říká stav — zelená schváleno/uhrazeno, oranžová čeká, červená odmítnutá nabídka. Klik ukáže malé okno s nejdůležitějšími údaji a tlačítkem, které otevře **PDF** v nové záložce; vedle je **Stáhnout**. Klient vidí **jen odeslané a dál** — rozepsanou nabídku ani rozepsanou fakturu nikdy, stornovanou taky ne. Objednávka vlastní PDF neměla, teď se skládá z toho, co klient odeslal (co, kolik, do kdy, jaké služby a výstupy, poznámka).

Sloupec **Přeposlechnuto** v klientském přehledu zanikl (1. 10. 2026) — kam poslech došel, je teď pod odkazem do AudioTaggeru v jednom sloupci **Přeposlech**. U klienta reklam zanikl i sloupec **Typ projektu**: je z něj ikona vedle názvu zakázky, stejně jako v našem přehledu, a název typu řekne bublinka nad ní.

Klient má v přehledu zakázek sloupec **Natáčecí plán** s tlačítkem **Zobrazit** — rozbalí se pod řádkem karta s domluvenými natáčeními: datum, čas, kdo čte a ve kterém studiu. Jsou v ní jen potvrzené termíny (u audioknihy potvrzené frekvence, u reklamy natáčení zapsané v kalendáři); co už je odtočené, je v seznamu šedě a označené. Rozjednané nabídky termínů, ze kterých si herec teprve vybírá, klient nevidí — ptal by se na něco, co se ještě změní. U odtočených termínů je i **strana textu, na které se ten den skončilo** (u dalších dnů rozsah „str. 96–141") — bere se ze zápisu zvukaře v chatu, který Bruno zapisuje k projektu. Kde zápis chybí, nic se neukáže.

- **Rodný list** — jen u rádiového spotu; PDF se vyrobí z údajů výstupu. K faktuře se přikládají rodné listy všech výstupů, které ho mají mít — když u některého chybí údaje, faktura neodejde a hláška řekne, u kterého výstupu co doplnit.
- **Tabule ve studiích** — obrazovka ve studiu s dnešním programem, poznámkami a tím, co chybí. Nahoře svítí, co právě běží — natáčení i střih; když jede víc věcí naráz, ostatní jsou pod tou hlavní jako „Zároveň“. Tabuli si může otevřít i člověk z týmu pod svým účtem: na kartě uživatele se zaškrtne **Přístup na tabule** a pak ji má rovnou v horní liště pod odkazem **Tabule** (a taky v Můj účet → Tabule ve studiu). Admin má odkaz Tabule vždycky a vybere si v něm, kterou pobočku otevřít. Z tabule se člověk z týmu vrátí tlačítkem **Zpět do portálu** v levém horním rohu (displej ve studiu ho nemá). Každé studio má **účet tabule** (jméno jako „brno1“ a heslo, bez e-mailu, spravuje se v Administraci → Studia); počítač u obrazovky se jím přihlásí v Chromu a portál rovnou ukáže tabuli toho studia. Do zbytku portálu se tímhle účtem nedostane. V okně vedle programu běží **příběhy z Instagramu** (když žádný není, poslední příspěvky) - účet se připojuje v Administraci → Studia a u každého studia jde okno vypnout.
- **Palubovka** (první záložka v **Přehledech**, jen pro toho, kdo ji má zapnutou; zatím Ondřej) — dva budíky jako v autě. **Tachometr** ukazuje, kolik je z měsíčního cíle vyfakturováno, a počítá přitom s tím, kolik je měsíce: desátého je na plánu třetina, ne celek. **Palivoměr** ukazuje, kolik korun je rozjednaných a ještě nevyfakturovaných, přepočteno na měsíce provozu — když klesne pod nastavenou hranici, je čas přidat na obchodu, a je to vidět dva měsíce předem. Pod budíky je fakturace po měsících za poslední rok s čárou cíle a seznam projektů, z čeho se bude fakturovat dál. Cíle (měsíční obrat, roční obrat, na kolik měsíců chceme mít rozjednáno) se zadávají rovnou na stránce; bez měsíčního cíle se měří proti průměru posledních tří měsíců. Budík nikdy nehlásí jen barvou — vedle ručičky stojí stav slovem.
- **Sítě** (jen pro toho, kdo má zaškrtnuté **Tvoří příspěvky na sítě**) — příprava příspěvků na **Instagram a LinkedIn**. Vyberete formát (stories 9:16, příspěvek 4:5 nebo čtverec, LinkedIn na šířku) a šablonu, a pak se v návrhu dá cokoli posunout a přepsat jako v Canvě: **text, obrázek a tvar** se tahají myší, rohem se mění velikost, Delete maže. Pozadí je barva, přechod nebo fotka se ztmavením. Vrstvy se zadávají v procentech plátna, takže **přepnutí formátu nic nerozhodí**. Vpravo je druhá záložka **Popisek**: napíšete, o čem příspěvek je, a **Bruno navrhne text i hashtagy** podle sítě (Instagram kratší a osobnější, LinkedIn věcnější) — dá se to přepsat a zkopírovat i s hashtagy. Hotový obrázek stáhnete tlačítkem **Stáhnout PNG** v plné velikosti. Publikování rovnou na sítě zatím není — čeká na schválení aplikace u Mety a LinkedInu.
- **Příběhy na Instagram** (přepracováno 6. 10. 2026) — **neškrtá se tu nic ke schválení**: kdo má zaškrtnuté *Posílá příběhy*, složí příběh a pustí ho ven sám. Právo mají všichni ze Zuzo-labůzo, produkce i zvukaři; k instagramovému účtu se přitom nikdo z nich nedostane — vyvěsí to portál. **NA TELEFONU JE TO JAKO INSTAGRAM** (7. 10. 2026): nejdřív je vidět mřížka toho, co je venku, a vpravo dole plovoucí **+**. Klepnutím se skládání otevře přes celou obrazovku — nahoře křížek a **Zveřejnit**, náhled se natáhne na zbylou výšku, text se po něm přetahuje prstem a pod tím je psaní s velikostí, barvou a podkladem. Uložit koncept, vyměnit fotku, začít znovu a smazat jsou pod třemi tečkami. Rozepsaný příběh křížek nezahodí — po opětovném otevření je tam, kde byl. **Kdo přijde ikonou Instagramu, má prázdný rámeček rovnou otevřený** (8. 10. 2026) — „+“ se už nemáčká. **HUDBA DO PŘÍBĚHU** (8. 10. 2026): pod fotkou se vybere skladba, jak dlouhý má příběh být (5, 10 nebo 15 vteřin) a odkud má skladba hrát — a dá se to rovnou poslechnout. U videa je navíc zaškrtávátko **Vypnout původní zvuk videa**. **Hudba z Instagramu přes API nejde** — kontejner příběhu bere jen obrázek nebo video a zmínky, žádnou hudební nálepku, a jejich licence platí jen uvnitř jejich aplikace. Hraje proto jen to, co si do portálu nahrajeme sami: skladba se **vypálí do souboru přímo v prohlížeči** ještě před nahráním, takže z fotky se stane krátké video. Skládání trvá tak dlouho, jak dlouhý je příběh, a stránka u toho musí zůstat otevřená. Bez vybrané skladby se nepřekódovává nic a video jde ven přesně takové, jaké přišlo z telefonu. Knihovnu skladeb spravuje produkce tlačítkem **Knihovna hudby** pod editorem (přidat, přejmenovat, vypnout, smazat) — nahrávat se má jen to, k čemu máme práva. Kdyby některý prohlížeč neuměl složit MP4, hudba se v něm vůbec nenabídne a napíše to. **Fotky a videa vidí celý tým** (8. 10. 2026): kdo má přístup na Příběhy, vidí i snímky kolegů, ne jen své — dřív se místo cizí fotky ukázal rozbitý obrázek. Jen **rozdělaný koncept zůstává soukromý**, ten vidí pouze jeho autor. Na počítači zůstává všechno při starém: vlevo se tvoří, vpravo je mřížka.
  - **Nahoře se tvoří:** vlevo text, vpravo živý náhled 9:16 s pruhem, účtem a textem tam, kde bude. Text se **přetáhne myší i prstem** a dá se u něj změnit velikost, zarovnání, barva a podklad. U fotky se text **vypálí do obrázku** (Instagram popisek u příběhů přes API nebere), u videa zůstává jen poznámkou.
  - **Tlačítka:** *Dát na Instagram* (jde to ven hned), *Uložit koncept*, *Vyměnit fotku*, *Začít znovu* a *Smazat*. Koncept vidí jen jeho autor a drží původní fotku i podobu textu, takže se dá otevřít a dodělat.
  - **Zmínky přes zavináč:** nabídka pod textem se staví z toho, co už kdo použil dřív. Pozor — zavináč se propíše do textu na obrázku, ale **klikací nálepku ani spolupráci Instagram přes API nalepit neumí**; na to se musí z telefonu.
  - **Pod tím je přehled:** co je **právě na Instagramu**, kdo to tam dal, kdy, a za jak dlouho to zmizí — **vypršený příběh z mřížky zmizí** (8. 10. 2026), místo po něm je zase prázdné (odpočet běží v prohlížeči, příběh vydrží 24 hodin). Pak koncepty a to, co **neprošlo** (i s důvodem a tlačítkem Zkusit znovu).
  - Soubor jde do úložiště rovnou z telefonu, takže projde i video (strop Vercelu 4,5 MB by přes portál nestačil). Fotka se ořížne na 1080×1920.
- **Sítě v levém panelu** (6. 10. 2026) — pod rychlými volbami jsou dvě zelené ikony na fialovém. První vede rovnou na **Příběhy na Instagram** a svítí na ní počet rozdělaných (koncepty a to, co Instagram nevzal), druhá na **Příspěvky na sítě**. Žádné rozbalování — do fronty se stejně kliklo dál. První ikonu vidí každý, kdo smí posílat příběhy, druhou jen ten, kdo má právo na příspěvky.

- **Na telefonu je portál čistší** (6. 10. 2026) — v mobilní aplikaci se **nevykresluje ozubené kolo s nastavením** (na žádné stránce; nastavuje se od stolu) ani **malé ikonky v řádcích projektů** — nabídka, faktura a stav přeposlechu. V úzkém řádku se lepily přes datum a prstem na ně nikdo netrefil. Na počítači zůstává všechno, jen se to schovává šířkou okna. Naopak **v tmavém pruhu pod lištou, u pravé hrany, přibyla na telefonu ikona Instagramu** — jedno kliknutí a člověk skládá příběh; záložka Sítě u levé hrany je na telefonu schovaná a příběh se fotí právě telefonem. **Ikona je jen na úvodní stránce** (seznam projektů, 8. 10. 2026) — na ostatních stránkách překrývala obsah.
- **Licenční list** — u ostatních reklam (ne u rádiového spotu). Vymezení licence ke spotu: **jeden list za každý výstup** a na něm všichni jeho herci. Vypadá to jako Výstupy: na řádku je název spotu, interpreti, délka a typ licence (klepnutím se přehazuje výhradní/nevýhradní), pod tečkami média, datum výroby a vystavení jen toho jednoho listu. Klient, objednatel, území, podmínky a podpis jsou společné celé zakázce a sedí pod **Společné údaje**; **Klient** je nad seznamem a pamatuje si ho projekt (u agenturní zakázky je to koncový zadavatel). V seznamu se dá chodit **šipkami**, **Enter** přepíše název, **Escape** změnu vezme zpět. Vpravo je náhled listu na A4, klepnutím přes celou obrazovku. Vystavený list visí na svém řádku a klient ho vidí v portálu — na Disk se neukládá; tlačítko **Stáhnout všechny** sbalí všechny listy zakázky do jednoho archivu.
- **Technické parametry** — jak se to má natočit a v čem odevzdat. Sedí v **kartě projektu** pod údaji a v **kanálu projektu v chatu** pod ikonou posuvníků: klepnutím vyskočí okno (zavře se klepnutím mimo nebo Escapem) a z něj vede proklik na detail projektu. Každé nakladatelství to má jinak, proto se parametry vedou jako **sady přiřazené firmám** — projekt si svou vezme podle klienta sám, a když firma vlastní nemá, použije se obecná. U reklam se ukáže jen to, co projekt doopravdy dělá: nábor voiceoveru, postprodukce (jinak pro online, jinak pro TV) nebo rádiový spot. Upravují se na jednom místě v Administraci → **Technické parametry**, takže změna bitrate platí hned pro všechny projekty té firmy. **Měnit je smí jen ten, kdo to má zaškrtnuté na kartě** (Ondřej a Peter) — zvukař je má ke čtení.
- **Přeposlech** — AudioTagger: poslech nahrávky a zápis chyb s časem a stranou scénáře. Jak daleko to je, hlásí **sluchátka** — v přehledu jako malé kolečko u ikony typu projektu, v detailu jako odznak v hlavičce: **oranžová**, jakmile je v AudioTaggeru aspoň jeden zápis, **zelená**, když je přeposlechnuto komplet. Najetím myší se ukáže, kolik chyb je zapsaných, kolik stop doposlechnutých a kolik procent textu.
- **Natáčecí protokol** — co se při natáčení stalo.
- **Poznámky** — vnitřní blok pod projektem: co je k zakázce potřeba vědět a nepatří do žádné kolonky. Kdokoliv z nás sem napíše poznámku, dole je vždycky **poznámka klienta z objednávky** (ta se nemaže, čte se rovnou z objednávky). Vidí je jen Žůžo-labůžo a produkce, zvukař ne.
- **Historie** — co se u projektu měnilo a jaké zprávy odešly klientovi.
- **Doklady** — nabídky, faktury, výdaje a smlouvy navázané na projekt. Jen admin. Odsud jde nový doklad (i výdaj, také k ukončenému projektu) rovnou založit, projekt i klient se předvyplní. **Cesta zpátky se neztratí** (7. 10. 2026): nad každým dokladem je linka historie — odkaz na **projekt**, ze kterého doklad vzniknul, a na **kartu firmy**. Kdo na doklad přišel **z projektu**, ten z něj vůbec nevypadne (7. 10. 2026): nad dokladem je **hlavička projektu** — název, stav, firma a tentýž pásek záložek, kde svítí Doklady. Kliknutí na kteroukoli záložku vrátí na projekt a rovnou ji otevře, „zpět" vede na Doklady u projektu a nadpis a záložky sekce Doklady se přitom nevykreslí, ať nejsou pásky dva. Kdo přišel ze seznamu v sekci Doklady, má „zpět" na ten seznam, jak byl zvyklý. Na projektu se tak dá hned dodělat zbytek a kartu firmy netreba hledat přes seznam Firem, když například při odeslání dokladu chybí e-mail. Odkaz na kartu firmy vidí jen ten, kdo má právo na sekci **Firmy**.

- **Z projektu rovnou na kartu firmy** (7. 10. 2026) — v kartě *Zakázka* na detailu projektu je pod výběrem firmy odkaz **Otevřít kartu firmy** (a komu se karta jen zobrazuje, ten má odkazem rovnou název firmy). Už se nemusí chodit přes seznam Firem v liště, když například chybí e-mail. Zase jen pro toho, kdo na Firmy právo má.

# Cesta zakázky

1. **Objednávka.** Klient ji pošle v portálu (audiokniha nebo reklama). **U reklamy je to průvodce krok za krokem**: název zakázky, co od nás chce (Natáčení voiceoveru / Zvuková postprodukce / Sound design — s ikonami a klidně víc naráz), představa o hlasu, termín a nakonec shrnutí s poznámkou a podklady. Herec i termín se dají přeskočit. Objednané služby přijdou i v mailu o nové objednávce. Vznikne projekt, kanál v chatu a složka na Disku, a nám přijde mail — tlačítko v něm vede **rovnou na detail toho projektu** a poznámka z objednávky je u projektu v záložce Poznámky. U Audiotéky se v objednávce navíc vyplní autor, překladatel a nakladatelství a z nich se sám složí **úvod a závěr audioknihy** (režie vždy Ondřej Černý) — klient ho může upravit nebo přepsat, v detailu projektu je vidět a dá se doladit. Cena v objednávce se počítá ze sazby za normostranu; u firmy, která si **cenu navrhuje sama** (zaškrtávátko na kartě firmy — takhle to má Albatros), se nepočítá nic: pole Počet normostran i Cena zůstávají a klient si je vyplní sám, sazba se u ní vůbec nenastavuje. **U audioknihy se rovnou založí nabídka** — jedna položka „Natáčení a postprodukce audioknihy" a cena z objednávky. Je **rozpracovaná**, takže klientovi sama neodejde: v Dokladech ▸ Nabídky se dá upravit a teprve pak odeslat. Když by se nezaložila (třeba objednávka bez ceny), zůstane v kartě projektu tlačítko **Přidat nabídku** jako dřív.
2. **Nabídka.** Vystaví se v Dokladech a odejde klientovi odkazem. Klient ji otevře, prohlédne a **schválí jedním kliknutím** — a na zvonečku to cinkne manažerovi projektu.
3. **Natáčení.** Produkce sestaví hercovi nabídku termínů, herec si z odkazu vybere, produkce potvrdí — a tím vzniká rezervace studia. **V den první frekvence se projekt sám překlopí na „Natáčíme“** (ráno, podle kalendáře) — díky tomu ho v chatu uvidí i zvukaři, kterým se projekt „V přípravě“ neukazuje. **U reklamy se to stane dřív:** jakmile mají v kalendáři termín **všichni herci zapsaní u projektu**, překlopí se na „Natáčíme“ hned — spot se naplánuje najednou a čekat s tím na den natáčení nemá smysl. Reklama bez vyplněných herců nebo naplánovaná po částech se překlopí dnem první frekvence jako audiokniha. **Zpátky to nikdy nejde:** smazaný termín stav nevrací, od té chvíle si ho řídí produkce. Smlouva s hercem se založí ze šablony a herec ji podepíše taky odkazem.
4. **Práce a nahrávky.** Zvukař si píše výkazy, nahrávky se ukládají na Disk a klient se k nim dostane odkazem z mailu — bez přihlašování. V přeposlechu píše, co chce opravit.
5. **Stav projektu** se během toho posouvá: V přípravě → Natáčíme → Dotočeno → Dokončeno - ke schválení → Schváleno - k fakturaci → Vyfakturováno. Podrobně je to v návodu *Stavy projektu a tlačítko Dotočeno*. **U reklam** fajfku *Dotočeno* nikdo neklikne — den po natáčení (podle kalendáře) ji hercům doplní Bruno sám, aby byli v seznamu zvýraznění. Nechodí u toho žádná zpráva ani nic do chatu a stav reklamy zůstává, kde je. Když je projekt ve stavu **Schváleno - k fakturaci** a faktura se klientovi odešle z portálu, portál se rovnou u faktury **zeptá „Ukončit projekt?"** — tlačítkem Ukončit projekt se stav přehodí na Vyfakturováno (tiše, do chatu se o tom nepíše, je to vidět v historii projektu), tlačítkem Nechat běžet zůstane, kde je. Samo se nic neukončí. V jiném stavu (třeba u zálohové faktury během natáčení) se portál neptá.
6. **Faktura.** Vystaví se z nabídky nebo rovnou u projektu. Projekt je hotový až fakturou.
7. **Platba.** Portál si třikrát denně stáhne pohyby z banky. Když sedí variabilní symbol i částka, **označí fakturu jako uhrazenou sám**; když sedí jen něco, nabídne to ke schválení.

# Lidé zvenčí nic neinstalují

Klient ani herec se nemusí nikam přihlašovat, když nechtějí. Portál posílá **odkaz, který funguje sám o sobě**: schválení nabídky, podpis smlouvy, stažení nahrávek, přeposlech, výběr termínů, vyplnění údajů. Odkaz je dlouhý a náhodný, stránka se nedá najít přes vyhledávač a jde kdykoliv zneplatnit a vygenerovat nový.

Klient, který účet má, vidí v portálu navíc své projekty, nahrávky a může objednávat.

# Kdo co vidí

- **Klient** — jen své projekty a nahrávky, ceny jen na svých dokladech. U rozpracovaných projektů vidí Progres natáčení.
- **Herec** — své termíny a údaje, smlouvy podepisuje odkazem. V Projektech vidí jen své projekty: název, Progres natáčení (válec: strana, kde se skončilo, proti počtu stran PDF s textem a kolik stran zbývá dotočit; po Dotočeno 100 %; u víc herců vážený součet podle normostran, ne průměr — kdo má natočit třetinu knihy, má na výsledku třetinový podíl), normostrany, stranu, kde se skončilo na poslední frekvenci, a odkaz na text (PDF končící _RE ze složky projektu). V Honorářích vidí, co je navrhnuto, co čeká na proplacení a co je zaplaceno, a odtud se dostane i ke svým smlouvám.
- **Zvukař** — projekty, kde pracuje, své výkazy a kalendář ke čtení. Nevidí rozpočty, doklady ani projekty v přípravě.
- **Produkce** — plánování, rozpočty, pozvánky herců. Nevidí doklady ani ceny objednávek.
- **Žůžo-labůžo (admin)** — všechno, včetně administrace.
- **Banka** je navíc: vidí ji jen ten, kdo to má u účtu zaškrtnuté, ani ostatní admini ne.
- **Nápověda** je naše: návod bez zaškrtnuté role vidí jen tým (Žůžo-labůžo, Produkce, Zvukař). Herec nebo klient uvidí jen návod, u kterého je v Adminu ▸ Návody ▸ „Komu se ukáže" zaškrtnutá jeho role — a jen tehdy se mu v liště objeví otazník.

# Co portál dělá sám

- **Páruje platby** z banky s fakturami (třikrát denně).
- **Upomíná faktury po splatnosti** — ve všední dny ráno, podle nastavení v Dokladech ▸ Upomínky. Tutéž upomínku nepošle dvakrát.
- **Hlídá opravy** — sedm dní po odevzdání, když klient nic neposlal, přehodí projekt na „Čekáme na opravy" a napíše mu.
- **Píše klientovi** zprávy o stavu projektu podle toho, co má jeho firma zapnuté; text se bere ze Vzorů zpráv. Navíc mu u audioknihy odejde zpráva **„Přeposlech dokončen"** ve chvíli, kdy v AudioTaggeru klepne na PŘEPOSLECHNUTO — že přeposlech máme kompletní a pouštíme se do finálních oprav. Tahle jediná chodí i bez zapnutí na kartě firmy (vypnout jde tamtéž, přepnutím na Neposílat); u reklamní firmy neodejde vůbec.
- **Čte účtárenskou schránku** a z příloh zakládá nezařazené výdaje — z účtenky si navíc přečte částku, datum i dodavatele.
- **Vyrobí rodný list** spotu, jakmile je reklama hotová.
- **Navrhne bonus** zvukaři, který odvedl většinu střihu.
- **Nabídne zvukaři výkaz** pět minut před koncem jeho natáčení, castingu nebo střihu v kalendáři — přijde upozornění do zvonečku i do mobilu a ve **Výkazech** čeká řádek, který se jedním klikem („Přidat výkaz") překlopí do výkazu. Produkce s tím nic nedělá.
- **Šestého v měsíci** pošle zvukařům přehled jejich výkazů za minulý měsíc.
- **Bruno** čte kanály projektů v chatu, pozná, kam se doteklo natáčení, a zapíše to do karty projektu. Když si není jistý, zeptá se v kanálu.
- **Bruno je zároveň nápověda k portálu** (23. 9. 2026). Napište mu do chatu — v kanálu přes „Bruno, …", v soukromé konverzaci rovnou — třeba „kde zapíšu výkaz", „co mě čeká zítra" nebo „jak je na tom Strabag". V soukromé zprávě a ve skupině si **sám sáhne do portálu**: do kalendáře, do projektů, do vašich úkolů a do návodů — a odpoví i s odkazem. Dívá se **vašima očima**: co vám role nepouští, to se nedozvíte ani od něj.

# Na čem to stojí

Portál běží na Vercelu, data jsou v databázi. Nahrávky bydlí na **Google Disku** (portál je jen ukazuje a stahuje), ostatní přílohy v úložišti s dočasnými odkazy. Kurzy měn se berou z **ČNB** a ukládají se k dokladu, údaje firem z **ARESu**. Pohyby na účtu portál bere z **upozornění, která banka posílá e-mailem** — kouká do vyhrazené schránky každé dvě minuty a platby páruje sám; ručně nahraný výpis ve formátu ABO je jen záloha na dotažení historie. E-maily chodí přes běžný SMTP, upozornění do mobilu přes push.

# Když něco hledáš

- **Kde je zakázka a jak na tom je?** Projekty → karta projektu → Přehled.
- **Kdy natáčíme a kde?** Kalendář, nebo záložka Natáčecí plán u projektu.
- **Chci kalendář v telefonu?** Kalendář → ikonka kalendáře s plusem vpravo nahoře (Google, Apple, Outlook; jen pro čtení).
- **Co jsme klientovi poslali?** Historie u projektu.
- **Kolik jsme fakturovali?** Doklady u projektu, nebo sekce Doklady.
- **Přišly peníze?** Doklady → Banka (kdo na ni má právo). Uhrazené faktury se označují samy, obvykle do pár minut od připsání.
- **Proč klientovi nic nepřišlo?** Firmy → karta firmy → Notifikace.
- **Kde jsou naše složky na Disku?** Nahrávky — vedle složky klienta se tam od 30. 9. 2026 nabízejí i naše vlastní složky (Klientská zóna, Dokumenty, Marketing). Každý vidí jen ty, které má na kartě účtu zaškrtnuté; kdo složku nemá, tomu se v přepínači vůbec neukáže. Zakládají se v Administraci → Složky na Disku. Pozor: rozhoduje to jen o tom, co ukáže portál — kdo si Disk otevře přímo v Googlu, uvidí všechno, co má jeho účet nasdílené.
- **Jak něco udělat?** Otazník v liště — tahle Nápověda.`,
};
