// Vygenerovane ze schema.prisma jen pro typovou kontrolu bez node_modules.
declare module '@prisma/client' {
  export type Role = 'CLIENT' | 'HEREC' | 'ADMIN' | 'ZVUKAR' | 'PRODUKCE' | 'ROBOT';
  export type CompanyType = 'KLIENT' | 'DODAVATEL';
  export type OrderStatus = 'NEW' | 'CONFIRMED' | 'IN_PROGRESS' | 'DONE' | 'CANCELLED';
  export type OrderKind = 'AUDIOBOOK' | 'AD';
  export type CaflouSyncStatus = 'SKIPPED' | 'PENDING' | 'OK' | 'ERROR';
  export type KomuNotifikace = 'NIKAM' | 'KLIENT' | 'INTERNE';
  export type ProjectSource = 'CAFLOU' | 'PORTAL';
  export type PaymentMethod = 'CARD' | 'CASH' | 'TRANSFER';
  export type ProjectPriority = 'LOW' | 'MEDIUM' | 'HIGH';
  export type DruhArchivu = 'FIRMA' | 'UZIVATEL' | 'PROJEKT';
  export type ChatUpozorneni = 'VSE' | 'ZMINKY' | 'NIC';
  export type DruhUdalosti = 'ZALOZENO' | 'ZMENA' | 'NOTIFIKACE' | 'BRUNO';
  export type WorkType = 'RECORDING' | 'EDITING' | 'OTHER';
  export type CaflouContactKind = 'NEZARAZENO' | 'KLIENT' | 'HEREC' | 'IGNOROVAT';
  export type ConversationKind = 'PROJEKT' | 'SOUKROMA' | 'SKUPINA' | 'DOTAZ';
  export type Currency = 'CZK' | 'EUR' | 'GBP' | 'USD';
  export type OfferStatus = 'DRAFT' | 'SENT' | 'APPROVED' | 'REJECTED';
  export type InvoiceStatus = 'DRAFT' | 'SENT' | 'PAID' | 'CANCELLED';
  export type RezimDph = 'STANDARD' | 'PRENESENA' | 'MIMO_PREDMET';
  export type JazykDokladu = 'CS' | 'EN';
  export type StavDokladu = 'NEZARAZENY' | 'ZARAZENY';
  export type ContractStatus = 'DRAFT' | 'SENT' | 'SIGNED' | 'REJECTED' | 'CANCELLED';
  export type ContractSignerRole = 'MEDIASPACE' | 'PROTISTRANA';
  export type StudioBlockKind = 'HOLIDAY' | 'VACATION' | 'MAINTENANCE' | 'INTERNAL' | 'OTHER' | 'NATACENI' | 'STRIH';
  export type RecordingStatus = 'DRAFT' | 'PREPARING' | 'SENT' | 'PICKING' | 'SUBMITTED' | 'RETURNED' | 'REJECTED' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED';
  export type SlotState = 'OFFERED' | 'SELECTED' | 'CONFIRMED' | 'RELEASED' | 'CANCELLED';
  export type FeedScope = 'MINE' | 'STUDIO' | 'ALL';
  export type StavBonusu = 'NAVRZENO' | 'SCHVALENO' | 'ZAMITNUTO';
  export type StavPripominky = 'NOVA' | 'HOTOVA';
  export type PozvankaDruh = 'HEREC' | 'FIRMA';
  export type PozvankaStav = 'CEKA' | 'VYPLNENA' | 'HOTOVA' | 'ZRUSENA';
  export type Company = {
    id: string;
    code: string | null;
    type: CompanyType;
    name: string;
    ratePerPage: number | null;
    caflouCompanyId: string | null;
    driveFolderUrl: string | null;
    dealsAudiobooks: boolean;
    dealsAds: boolean;
    audioknihyNaKlic: boolean;
    contactName: string | null;
    fakturyKlientovi: boolean;
    contactEmail: string | null;
    contactPhone: string | null;
    ic: string | null;
    dic: string | null;
    vatPayer: boolean;
    bankAccount: string | null;
    address: string | null;
    addressStreet: string | null;
    addressCity: string | null;
    addressZip: string | null;
    addressCountry: string | null;
    paymentTermDays: number | null;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type User = {
    id: string;
    code: string | null;
    email: string;
    passwordHash: string;
    name: string | null;
    phone: string | null;
    role: Role;
    companyId: string | null;
    active: boolean;
    createdAt: Date;
    birthDate: Date | null;
    photoUrl: string | null;
    maFotku: boolean;
    hourlyRate: number | null;
    manazerProjektu: boolean;
    smlouvyPodepisuje: boolean;
    podpisSmluv: string | null;
    prijimaDotazyKlientu: boolean;
    vidiBanku: boolean;
    sledujeZmenyProjektu: boolean;
    chatUpozorneniZpravy: ChatUpozorneni;
    chatUpozorneniSkupiny: ChatUpozorneni;
    chatUpozorneniKanaly: ChatUpozorneni;
    chatTichoOd: number | null;
    chatTichoDo: number | null;
    dostavaDotoceno: boolean;
    dostavaDotocenoKlient: boolean;
    dostavaObjednavky: boolean;
    dostavaVyplneneUdaje: boolean;
    vychoziManazerAudioknih: boolean;
    dodavatelCompanyId: string | null;
    birthNumber: string | null;
    ic: string | null;
    dic: string | null;
    vatPayer: boolean;
    bankAccount: string | null;
    addressStreet: string | null;
    addressCity: string | null;
    addressZip: string | null;
    addressCountry: string | null;
    udajeDoplneny: boolean;
    inviteToken: string | null;
    inviteTokenExpires: Date | null;
    invitedAt: Date | null;
    passwordSetAt: Date | null;
    [key: string]: any;
  };
  export type Order = {
    id: string;
    companyId: string;
    createdByUserId: string;
    kind: OrderKind;
    title: string;
    pageCount: number | null;
    ratePerPageSnapshot: number | null;
    priceEstimate: number | null;
    deadline: Date | null;
    note: string | null;
    preferredNarrator: string | null;
    attachmentUrl: string | null;
    attachmentName: string | null;
    status: OrderStatus;
    emailSentAt: Date | null;
    caflouProjectId: string | null;
    caflouSyncStatus: CaflouSyncStatus;
    caflouSyncError: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type Project = {
    id: string;
    companyId: string;
    orderId: string | null;
    name: string;
    status: string | null;
    narrator: string | null;
    finishDate: Date | null;
    releaseDate: Date | null;
    caflouProjectId: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type Counter = {
    name: string;
    value: number;
    [key: string]: any;
  };
  export type ProjectMeta = {
    id: string;
    caflouProjectId: string;
    driveUrl: string | null;
    managerUserId: string | null;
    priority: ProjectPriority | null;
    projectType: string | null;
    actorUserId: string | null;
    klientUserId: string | null;
    klientName: string | null;
    spotName: string | null;
    spotLengthSeconds: number | null;
    directorName: string | null;
    rlClientName: string | null;
    musicTitle: string | null;
    musicAuthor: string | null;
    noMusic: boolean;
    productionDate: Date | null;
    lastCaflouStatus: string | null;
    rlError: string | null;
    name: string | null;
    companyId: string | null;
    companyName: string | null;
    statusName: string | null;
    finished: boolean;
    pageCount: number | null;
    narrator: string | null;
    releaseDate: Date | null;
    startDate: Date | null;
    endDate: Date | null;
    popis: string | null;
    licenceUziti: string | null;
    dotocenoStavPred: string | null;
    dotocenoStavPo: string | null;
    zdroj: ProjectSource;
    prenesenoAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type Archiv = {
    id: string;
    druh: DruhArchivu;
    nazev: string;
    puvodniId: string;
    souhrn: string;
    pocetZaznamu: number;
    obsah: any;
    uzivatelId: string | null;
    uzivatelJmeno: string | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type ProjektUdalost = {
    id: string;
    caflouProjectId: string;
    druh: DruhUdalosti;
    pole: string | null;
    popis: string;
    predchozi: string | null;
    nova: string | null;
    uzivatelId: string | null;
    uzivatelJmeno: string | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type NotifikaceFirmy = {
    id: string;
    companyId: string;
    stav: string;
    komu: KomuNotifikace;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type NotifikaceOdeslana = {
    id: string;
    caflouProjectId: string;
    znacka: string;
    prijemci: string;
    odeslanoAt: Date;
    [key: string]: any;
  };
  export type PriceListItem = {
    id: string;
    name: string;
    priceExVat: number | null;
    priceIncVat: number | null;
    active: boolean;
    rodnyList: boolean;
    proObjednavkyAudioknih: boolean;
    ikona: string | null;
    sortOrder: number;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type TimesheetEntry = {
    id: string;
    userId: string;
    date: Date;
    startMinutes: number;
    endMinutes: number;
    workType: WorkType;
    caflouProjectId: string | null;
    projectName: string | null;
    hourlyRateSnapshot: number;
    note: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type BudgetSettings = {
    id: string;
    pagesPerSession: number;
    sessionHours: number;
    editingCoefficient: number;
    bonusPerPage: number;
    hourlyRate: number;
    holdHours: number;
    updatedAt: Date;
    [key: string]: any;
  };
  export type UserQuickAction = {
    id: string;
    userId: string;
    actionKey: string;
    sortOrder: number;
    createdAt: Date;
    [key: string]: any;
  };
  export type UserMenuItem = {
    id: string;
    userId: string;
    label: string;
    href: string;
    sortOrder: number;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type CaflouCompany = {
    id: string;
    name: string;
    ic: string | null;
    dic: string | null;
    email: string | null;
    phone: string | null;
    addressStreet: string | null;
    addressCity: string | null;
    addressZip: string | null;
    addressCountry: string | null;
    note: string | null;
    kind: CaflouContactKind;
    kindReason: string | null;
    raw: any;
    importedAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type Conversation = {
    id: string;
    kind: ConversationKind;
    name: string | null;
    caflouProjectId: string | null;
    dotazProjektId: string | null;
    dotazCompanyId: string | null;
    uzavrenoAt: Date | null;
    vsichni: boolean;
    createdById: string;
    createdAt: Date;
    lastMessageAt: Date;
    [key: string]: any;
  };
  export type ConversationMember = {
    id: string;
    conversationId: string;
    userId: string;
    lastReadAt: Date;
    ztlumeno: boolean;
    pripnuto: boolean;
    poradiPripnuti: number | null;
    upozorneni: ChatUpozorneni | null;
    skryto: boolean;
    skrytoAt: Date | null;
    [key: string]: any;
  };
  export type Message = {
    id: string;
    conversationId: string;
    userId: string;
    body: string;
    createdAt: Date;
    editedAt: Date | null;
    parentId: string | null;
    [key: string]: any;
  };
  export type PushOdber = {
    id: string;
    userId: string;
    endpoint: string;
    p256dh: string;
    auth: string;
    zarizeni: string | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type MessageAttachment = {
    id: string;
    messageId: string;
    key: string;
    name: string;
    mime: string;
    size: number;
    createdAt: Date;
    [key: string]: any;
  };
  export type MessageReaction = {
    id: string;
    messageId: string;
    userId: string;
    code: string;
    createdAt: Date;
    [key: string]: any;
  };
  export type Task = {
    id: string;
    userId: string;
    title: string;
    done: boolean;
    dueDate: Date | null;
    sortOrder: number;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type IssuerCompany = {
    id: string;
    name: string;
    ic: string | null;
    dic: string | null;
    vatPayer: boolean;
    addressStreet: string | null;
    addressCity: string | null;
    addressZip: string | null;
    addressCountry: string | null;
    email: string | null;
    phone: string | null;
    logoUrl: string | null;
    invoiceNumberFormat: string;
    invoiceNextNumber: number;
    offerNumberFormat: string;
    offerNextNumber: number;
    contractNumberFormat: string;
    contractNextNumber: number;
    defaultCurrency: Currency;
    isDefault: boolean;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type BankAccount = {
    id: string;
    issuerCompanyId: string;
    label: string;
    accountNumber: string | null;
    iban: string | null;
    swift: string | null;
    bankName: string | null;
    currency: Currency;
    isDefault: boolean;
    sortOrder: number;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type Offer = {
    id: string;
    number: string;
    issuerCompanyId: string;
    companyId: string;
    currency: Currency;
    issueDate: Date;
    validUntil: Date | null;
    subject: string | null;
    note: string | null;
    jazyk: JazykDokladu;
    status: OfferStatus;
    approvalToken: string;
    sentAt: Date | null;
    odeslalUserId: string | null;
    approvedAt: Date | null;
    approvedByName: string | null;
    rejectedAt: Date | null;
    caflouProjectId: string | null;
    projectName: string | null;
    slevaProcent: number;
    slevaMinor: number;
    slevaPopis: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type OfferItem = {
    id: string;
    offerId: string;
    description: string;
    quantity: number;
    unit: string | null;
    unitPriceMinor: number;
    vatRate: number;
    sortOrder: number;
    [key: string]: any;
  };
  export type Invoice = {
    id: string;
    number: string;
    variableSymbol: string;
    issuerCompanyId: string;
    companyId: string;
    bankAccountId: string | null;
    currency: Currency;
    exchangeRate: number;
    exchangeRateDate: Date | null;
    issueDate: Date;
    taxDate: Date | null;
    dueDate: Date | null;
    subject: string | null;
    note: string | null;
    rezimDph: RezimDph;
    jazyk: JazykDokladu;
    status: InvoiceStatus;
    sentAt: Date | null;
    paidAt: Date | null;
    paidAmountMinor: number | null;
    offerId: string | null;
    caflouProjectId: string | null;
    projectName: string | null;
    slevaProcent: number;
    slevaMinor: number;
    slevaPopis: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type OdeslaniFaktury = {
    id: string;
    invoiceId: string;
    odeslalId: string | null;
    odeslalJmeno: string | null;
    sPrilohou: boolean;
    sRodnymListem: boolean;
    createdAt: Date;
    [key: string]: any;
  };
  export type InvoiceItem = {
    id: string;
    invoiceId: string;
    description: string;
    quantity: number;
    unit: string | null;
    unitPriceMinor: number;
    vatRate: number;
    sortOrder: number;
    [key: string]: any;
  };
  export type ExpenseCategory = {
    id: string;
    name: string;
    sortOrder: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type Expense = {
    id: string;
    number: string | null;
    supplierCompanyId: string | null;
    supplierName: string | null;
    categoryId: string | null;
    issuerCompanyId: string | null;
    currency: Currency;
    exchangeRate: number;
    exchangeRateDate: Date | null;
    description: string | null;
    amountExVatMinor: number;
    vatRate: number;
    issueDate: Date;
    dueDate: Date | null;
    paid: boolean;
    paidAt: Date | null;
    paymentMethod: PaymentMethod;
    attachmentUrl: string | null;
    attachmentName: string | null;
    supplierAccount: string | null;
    note: string | null;
    caflouProjectId: string | null;
    projectName: string | null;
    stav: StavDokladu;
    zdroj: string | null;
    mailKlic: string | null;
    mailOd: string | null;
    mailPredmet: string | null;
    mailPrijatoAt: Date | null;
    navrhJson: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type PostaStav = {
    id: string;
    posledniUid: number;
    posledniKontrolaAt: Date | null;
    posledniChyba: string | null;
    nactenoCelkem: number;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type ColumnLabel = {
    id: string;
    tableKey: string;
    columnKey: string;
    label: string;
    sortOrder: number;
    hidden: boolean;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type ContractTemplate = {
    id: string;
    name: string;
    body: string;
    active: boolean;
    sortOrder: number;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type Contract = {
    id: string;
    number: string;
    title: string;
    body: string;
    issuerCompanyId: string;
    companyId: string | null;
    signerName: string;
    signerEmail: string;
    caflouProjectId: string | null;
    projectName: string | null;
    status: ContractStatus;
    accessToken: string;
    sentAt: Date | null;
    completedAt: Date | null;
    rejectedAt: Date | null;
    rejectedReason: string | null;
    bodyHash: string | null;
    odmenaText: string | null;
    splatnostText: string | null;
    actorUserId: string | null;
    vydajId: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type ContractSignature = {
    id: string;
    contractId: string;
    role: ContractSignerRole;
    name: string;
    email: string | null;
    imageData: string;
    signedAt: Date;
    ip: string | null;
    userAgent: string | null;
    documentHash: string;
    stranekCelkem: number | null;
    stranekPotvrzeno: number | null;
    [key: string]: any;
  };
  export type Studio = {
    id: string;
    name: string;
    shortName: string;
    location: string | null;
    color: string;
    timezone: string;
    sortOrder: number;
    active: boolean;
    parentStudioId: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type StudioHours = {
    id: string;
    studioId: string;
    weekday: number;
    startMinutes: number;
    endMinutes: number;
    byArrangement: boolean;
    [key: string]: any;
  };
  export type StudioSlotPreset = {
    id: string;
    studioId: string;
    label: string;
    startMinutes: number;
    endMinutes: number;
    sortOrder: number;
    [key: string]: any;
  };
  export type StudioBlock = {
    id: string;
    studioId: string;
    start: Date;
    end: Date;
    kind: StudioBlockKind;
    title: string;
    note: string | null;
    caflouProjectId: string | null;
    projectName: string | null;
    actorUserId: string | null;
    actorName: string | null;
    zvukarUserId: string | null;
    zvukarName: string | null;
    createdById: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type RecordingRequest = {
    id: string;
    caflouProjectId: string;
    projectName: string;
    companyId: string | null;
    actorUserId: string | null;
    actorName: string;
    actorEmail: string;
    studioId: string;
    pageCount: number | null;
    requiredSessions: number;
    sessionMinutes: number;
    periodFrom: Date;
    periodTo: Date;
    note: string | null;
    actorNote: string | null;
    decisionNote: string | null;
    status: RecordingStatus;
    accessToken: string;
    holdUntil: Date | null;
    createdById: string;
    sentAt: Date | null;
    openedAt: Date | null;
    submittedAt: Date | null;
    decidedAt: Date | null;
    decidedById: string | null;
    completedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type RecordingSlot = {
    id: string;
    requestId: string;
    studioId: string;
    start: Date;
    end: Date;
    state: SlotState;
    selectedAt: Date | null;
    note: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type RecordingEvent = {
    id: string;
    requestId: string;
    slotId: string | null;
    userId: string | null;
    actorLabel: string;
    type: string;
    fromStatus: string | null;
    toStatus: string | null;
    note: string | null;
    payload: any | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type Notification = {
    id: string;
    userId: string;
    kind: string;
    title: string;
    body: string | null;
    url: string | null;
    readAt: Date | null;
    emailedAt: Date | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type CalendarFeed = {
    id: string;
    userId: string;
    token: string;
    scope: FeedScope;
    studioId: string | null;
    revokedAt: Date | null;
    lastReadAt: Date | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type RodnyList = {
    id: string;
    caflouProjectId: string;
    projectName: string;
    companyId: string | null;
    version: number;
    fileName: string;
    url: string;
    driveFileId: string | null;
    driveUrl: string | null;
    driveError: string | null;
    clientName: string;
    spotName: string;
    spotLength: string;
    director: string;
    musicTitle: string | null;
    musicAuthor: string | null;
    productionDate: Date;
    createdByUserId: string | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type CaflouProjectsCache = {
    key: string;
    payload: string;
    count: number;
    fetchedAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type PreposlechChyba = {
    id: string;
    caflouProjectId: string;
    trackIndex: number;
    trackName: string;
    localTime: number;
    pdfPage: number | null;
    zvyrazneni: any | null;
    description: string;
    createdByUserId: string | null;
    createdByName: string | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type PreposlechStav = {
    caflouProjectId: string;
    reviewed: boolean;
    reviewedAt: Date | null;
    reviewedByName: string | null;
    pocetStop: number;
    stopyZjistenyAt: Date | null;
    updatedAt: Date;
    [key: string]: any;
  };
  export type PreposlechStopa = {
    id: string;
    caflouProjectId: string;
    trackIndex: number;
    trackName: string;
    poslechnutoAt: Date;
    kdo: string | null;
    hotovoAt: Date | null;
    hotovoKdo: string | null;
    [key: string]: any;
  };
  export type PreposlechOdkaz = {
    token: string;
    caflouProjectId: string;
    createdAt: Date;
    createdByName: string | null;
    zneplatnenoAt: Date | null;
    otevrenoAt: Date | null;
    pocetOtevreni: number;
    [key: string]: any;
  };
  export type HerecDotocen = {
    id: string;
    caflouProjectId: string;
    userId: string;
    dotocenoAt: Date;
    potvrdilUserId: string | null;
    potvrdilJmeno: string | null;
    [key: string]: any;
  };
  export type VzorZpravy = {
    druh: string;
    stav: string;
    predmet: string | null;
    nadpis: string | null;
    text: string;
    audiotagger: boolean | null;
    upravilJmeno: string | null;
    updatedAt: Date;
    [key: string]: any;
  };
  export type NastaveniOznameni = {
    klic: string;
    zapnuto: boolean;
    zmenilJmeno: string | null;
    updatedAt: Date;
    [key: string]: any;
  };
  export type MesicniPrehledOdeslan = {
    id: string;
    userId: string;
    mesic: string;
    prijemce: string | null;
    odeslanoAt: Date;
    [key: string]: any;
  };
  export type BonusZvukare = {
    id: string;
    caflouProjectId: string;
    projectName: string | null;
    userId: string;
    castka: number;
    podilProcent: number;
    minutZvukare: number;
    minutCelkem: number;
    stav: StavBonusu;
    rucne: boolean;
    navrzenoAt: Date;
    rozhodnutoAt: Date | null;
    rozhodlId: string | null;
    rozhodlJmeno: string | null;
    poznamka: string | null;
    [key: string]: any;
  };
  export type ProjektNaklad = {
    id: string;
    caflouProjectId: string;
    nazev: string;
    castka: number;
    poradi: number;
    createdAt: Date;
    [key: string]: any;
  };
  export type PreposlechPozice = {
    id: string;
    caflouProjectId: string;
    posluchac: string;
    trackIndex: number;
    localTime: number;
    jmeno: string | null;
    hraje: boolean;
    updatedAt: Date;
    [key: string]: any;
  };
  export type BrunoNatoceno = {
    id: string;
    caflouProjectId: string;
    userId: string | null;
    strana: number;
    zdrojMessageId: string | null;
    zapsalUserId: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type BrunoPamet = {
    id: string;
    caflouProjectId: string | null;
    poznamka: string;
    createdAt: Date;
    [key: string]: any;
  };
  export type BrunoPrirucka = {
    id: string;
    text: string;
    updatedAt: Date;
    updatedBy: string | null;
    [key: string]: any;
  };
  export type ChatPise = {
    id: string;
    conversationId: string;
    userId: string;
    updatedAt: Date;
    [key: string]: any;
  };
  export type PreposlechUdalost = {
    id: string;
    caflouProjectId: string;
    typ: string;
    popis: string;
    kdo: string | null;
    chybaId: string | null;
    snimek: any | null;
    vracenoAt: Date | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type PripominkaPortalu = {
    id: string;
    userId: string;
    text: string;
    odkud: string | null;
    stav: StavPripominky;
    hotovoAt: Date | null;
    hotovoById: string | null;
    hotovoJmeno: string | null;
    poznamka: string | null;
    podobnaId: string | null;
    createdAt: Date;
    [key: string]: any;
  };
  export type PripominkaPriloha = {
    id: string;
    pripominkaId: string;
    url: string;
    nazev: string;
    createdAt: Date;
    [key: string]: any;
  };
  export type PozvankaUdaju = {
    id: string;
    token: string;
    druh: PozvankaDruh;
    stav: PozvankaStav;
    userId: string | null;
    companyId: string | null;
    jmeno: string | null;
    email: string | null;
    platiDo: Date;
    vytvorilId: string | null;
    createdAt: Date;
    odeslanoAt: Date | null;
    vyplnenoAt: Date | null;
    zpracovanoAt: Date | null;
    data: any | null;
    poznamka: string | null;
    vzkazOdNej: string | null;
    [key: string]: any;
  };
  export type Navod = {
    id: string;
    slug: string;
    nazev: string;
    perex: string | null;
    kategorie: string;
    obsah: string;
    hledaci: string;
    poradi: number;
    zverejneno: boolean;
    autorId: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type BankConnection = {
    id: string;
    institutionId: string;
    institutionName: string;
    requisitionId: string;
    agreementId: string | null;
    accountId: string | null;
    iban: string | null;
    label: string | null;
    issuerCompanyId: string | null;
    stav: string;
    consentExpiresAt: Date | null;
    lastSyncAt: Date | null;
    lastSyncError: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type BankTransaction = {
    id: string;
    connectionId: string;
    externalId: string;
    bookedAt: Date;
    amountMinor: number;
    currency: Currency;
    variableSymbol: string | null;
    counterpartyName: string | null;
    counterpartyAccount: string | null;
    reference: string | null;
    invoiceId: string | null;
    stav: string;
    navrhInvoiceId: string | null;
    navrhDuvod: string | null;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export type DruhLicence = {
    id: string;
    nazev: string;
    ikona: string | null;
    poradi: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    [key: string]: any;
  };
  export class PrismaClient {
    constructor(args?: any);
    $transaction(arg: any, opts?: any): Promise<any>;
    $connect(): Promise<void>;
    $disconnect(): Promise<void>;
    $queryRaw(...args: any[]): Promise<any>;
    $executeRaw(...args: any[]): Promise<any>;
    company: {
      findUnique(args?: any): Promise<Company | null>;
      findFirst(args?: any): Promise<Company | null>;
      findMany(args?: any): Promise<Company[]>;
      create(args?: any): Promise<Company>;
      update(args?: any): Promise<Company>;
      upsert(args?: any): Promise<Company>;
      delete(args?: any): Promise<Company>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    user: {
      findUnique(args?: any): Promise<User | null>;
      findFirst(args?: any): Promise<User | null>;
      findMany(args?: any): Promise<User[]>;
      create(args?: any): Promise<User>;
      update(args?: any): Promise<User>;
      upsert(args?: any): Promise<User>;
      delete(args?: any): Promise<User>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    order: {
      findUnique(args?: any): Promise<Order | null>;
      findFirst(args?: any): Promise<Order | null>;
      findMany(args?: any): Promise<Order[]>;
      create(args?: any): Promise<Order>;
      update(args?: any): Promise<Order>;
      upsert(args?: any): Promise<Order>;
      delete(args?: any): Promise<Order>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    project: {
      findUnique(args?: any): Promise<Project | null>;
      findFirst(args?: any): Promise<Project | null>;
      findMany(args?: any): Promise<Project[]>;
      create(args?: any): Promise<Project>;
      update(args?: any): Promise<Project>;
      upsert(args?: any): Promise<Project>;
      delete(args?: any): Promise<Project>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    counter: {
      findUnique(args?: any): Promise<Counter | null>;
      findFirst(args?: any): Promise<Counter | null>;
      findMany(args?: any): Promise<Counter[]>;
      create(args?: any): Promise<Counter>;
      update(args?: any): Promise<Counter>;
      upsert(args?: any): Promise<Counter>;
      delete(args?: any): Promise<Counter>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    projectMeta: {
      findUnique(args?: any): Promise<ProjectMeta | null>;
      findFirst(args?: any): Promise<ProjectMeta | null>;
      findMany(args?: any): Promise<ProjectMeta[]>;
      create(args?: any): Promise<ProjectMeta>;
      update(args?: any): Promise<ProjectMeta>;
      upsert(args?: any): Promise<ProjectMeta>;
      delete(args?: any): Promise<ProjectMeta>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    archiv: {
      findUnique(args?: any): Promise<Archiv | null>;
      findFirst(args?: any): Promise<Archiv | null>;
      findMany(args?: any): Promise<Archiv[]>;
      create(args?: any): Promise<Archiv>;
      update(args?: any): Promise<Archiv>;
      upsert(args?: any): Promise<Archiv>;
      delete(args?: any): Promise<Archiv>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    projektUdalost: {
      findUnique(args?: any): Promise<ProjektUdalost | null>;
      findFirst(args?: any): Promise<ProjektUdalost | null>;
      findMany(args?: any): Promise<ProjektUdalost[]>;
      create(args?: any): Promise<ProjektUdalost>;
      update(args?: any): Promise<ProjektUdalost>;
      upsert(args?: any): Promise<ProjektUdalost>;
      delete(args?: any): Promise<ProjektUdalost>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    notifikaceFirmy: {
      findUnique(args?: any): Promise<NotifikaceFirmy | null>;
      findFirst(args?: any): Promise<NotifikaceFirmy | null>;
      findMany(args?: any): Promise<NotifikaceFirmy[]>;
      create(args?: any): Promise<NotifikaceFirmy>;
      update(args?: any): Promise<NotifikaceFirmy>;
      upsert(args?: any): Promise<NotifikaceFirmy>;
      delete(args?: any): Promise<NotifikaceFirmy>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    notifikaceOdeslana: {
      findUnique(args?: any): Promise<NotifikaceOdeslana | null>;
      findFirst(args?: any): Promise<NotifikaceOdeslana | null>;
      findMany(args?: any): Promise<NotifikaceOdeslana[]>;
      create(args?: any): Promise<NotifikaceOdeslana>;
      update(args?: any): Promise<NotifikaceOdeslana>;
      upsert(args?: any): Promise<NotifikaceOdeslana>;
      delete(args?: any): Promise<NotifikaceOdeslana>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    priceListItem: {
      findUnique(args?: any): Promise<PriceListItem | null>;
      findFirst(args?: any): Promise<PriceListItem | null>;
      findMany(args?: any): Promise<PriceListItem[]>;
      create(args?: any): Promise<PriceListItem>;
      update(args?: any): Promise<PriceListItem>;
      upsert(args?: any): Promise<PriceListItem>;
      delete(args?: any): Promise<PriceListItem>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    timesheetEntry: {
      findUnique(args?: any): Promise<TimesheetEntry | null>;
      findFirst(args?: any): Promise<TimesheetEntry | null>;
      findMany(args?: any): Promise<TimesheetEntry[]>;
      create(args?: any): Promise<TimesheetEntry>;
      update(args?: any): Promise<TimesheetEntry>;
      upsert(args?: any): Promise<TimesheetEntry>;
      delete(args?: any): Promise<TimesheetEntry>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    budgetSettings: {
      findUnique(args?: any): Promise<BudgetSettings | null>;
      findFirst(args?: any): Promise<BudgetSettings | null>;
      findMany(args?: any): Promise<BudgetSettings[]>;
      create(args?: any): Promise<BudgetSettings>;
      update(args?: any): Promise<BudgetSettings>;
      upsert(args?: any): Promise<BudgetSettings>;
      delete(args?: any): Promise<BudgetSettings>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    userQuickAction: {
      findUnique(args?: any): Promise<UserQuickAction | null>;
      findFirst(args?: any): Promise<UserQuickAction | null>;
      findMany(args?: any): Promise<UserQuickAction[]>;
      create(args?: any): Promise<UserQuickAction>;
      update(args?: any): Promise<UserQuickAction>;
      upsert(args?: any): Promise<UserQuickAction>;
      delete(args?: any): Promise<UserQuickAction>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    userMenuItem: {
      findUnique(args?: any): Promise<UserMenuItem | null>;
      findFirst(args?: any): Promise<UserMenuItem | null>;
      findMany(args?: any): Promise<UserMenuItem[]>;
      create(args?: any): Promise<UserMenuItem>;
      update(args?: any): Promise<UserMenuItem>;
      upsert(args?: any): Promise<UserMenuItem>;
      delete(args?: any): Promise<UserMenuItem>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    caflouCompany: {
      findUnique(args?: any): Promise<CaflouCompany | null>;
      findFirst(args?: any): Promise<CaflouCompany | null>;
      findMany(args?: any): Promise<CaflouCompany[]>;
      create(args?: any): Promise<CaflouCompany>;
      update(args?: any): Promise<CaflouCompany>;
      upsert(args?: any): Promise<CaflouCompany>;
      delete(args?: any): Promise<CaflouCompany>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    conversation: {
      findUnique(args?: any): Promise<Conversation | null>;
      findFirst(args?: any): Promise<Conversation | null>;
      findMany(args?: any): Promise<Conversation[]>;
      create(args?: any): Promise<Conversation>;
      update(args?: any): Promise<Conversation>;
      upsert(args?: any): Promise<Conversation>;
      delete(args?: any): Promise<Conversation>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    conversationMember: {
      findUnique(args?: any): Promise<ConversationMember | null>;
      findFirst(args?: any): Promise<ConversationMember | null>;
      findMany(args?: any): Promise<ConversationMember[]>;
      create(args?: any): Promise<ConversationMember>;
      update(args?: any): Promise<ConversationMember>;
      upsert(args?: any): Promise<ConversationMember>;
      delete(args?: any): Promise<ConversationMember>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    message: {
      findUnique(args?: any): Promise<Message | null>;
      findFirst(args?: any): Promise<Message | null>;
      findMany(args?: any): Promise<Message[]>;
      create(args?: any): Promise<Message>;
      update(args?: any): Promise<Message>;
      upsert(args?: any): Promise<Message>;
      delete(args?: any): Promise<Message>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    pushOdber: {
      findUnique(args?: any): Promise<PushOdber | null>;
      findFirst(args?: any): Promise<PushOdber | null>;
      findMany(args?: any): Promise<PushOdber[]>;
      create(args?: any): Promise<PushOdber>;
      update(args?: any): Promise<PushOdber>;
      upsert(args?: any): Promise<PushOdber>;
      delete(args?: any): Promise<PushOdber>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    messageAttachment: {
      findUnique(args?: any): Promise<MessageAttachment | null>;
      findFirst(args?: any): Promise<MessageAttachment | null>;
      findMany(args?: any): Promise<MessageAttachment[]>;
      create(args?: any): Promise<MessageAttachment>;
      update(args?: any): Promise<MessageAttachment>;
      upsert(args?: any): Promise<MessageAttachment>;
      delete(args?: any): Promise<MessageAttachment>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    messageReaction: {
      findUnique(args?: any): Promise<MessageReaction | null>;
      findFirst(args?: any): Promise<MessageReaction | null>;
      findMany(args?: any): Promise<MessageReaction[]>;
      create(args?: any): Promise<MessageReaction>;
      update(args?: any): Promise<MessageReaction>;
      upsert(args?: any): Promise<MessageReaction>;
      delete(args?: any): Promise<MessageReaction>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    task: {
      findUnique(args?: any): Promise<Task | null>;
      findFirst(args?: any): Promise<Task | null>;
      findMany(args?: any): Promise<Task[]>;
      create(args?: any): Promise<Task>;
      update(args?: any): Promise<Task>;
      upsert(args?: any): Promise<Task>;
      delete(args?: any): Promise<Task>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    issuerCompany: {
      findUnique(args?: any): Promise<IssuerCompany | null>;
      findFirst(args?: any): Promise<IssuerCompany | null>;
      findMany(args?: any): Promise<IssuerCompany[]>;
      create(args?: any): Promise<IssuerCompany>;
      update(args?: any): Promise<IssuerCompany>;
      upsert(args?: any): Promise<IssuerCompany>;
      delete(args?: any): Promise<IssuerCompany>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    bankAccount: {
      findUnique(args?: any): Promise<BankAccount | null>;
      findFirst(args?: any): Promise<BankAccount | null>;
      findMany(args?: any): Promise<BankAccount[]>;
      create(args?: any): Promise<BankAccount>;
      update(args?: any): Promise<BankAccount>;
      upsert(args?: any): Promise<BankAccount>;
      delete(args?: any): Promise<BankAccount>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    offer: {
      findUnique(args?: any): Promise<Offer | null>;
      findFirst(args?: any): Promise<Offer | null>;
      findMany(args?: any): Promise<Offer[]>;
      create(args?: any): Promise<Offer>;
      update(args?: any): Promise<Offer>;
      upsert(args?: any): Promise<Offer>;
      delete(args?: any): Promise<Offer>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    offerItem: {
      findUnique(args?: any): Promise<OfferItem | null>;
      findFirst(args?: any): Promise<OfferItem | null>;
      findMany(args?: any): Promise<OfferItem[]>;
      create(args?: any): Promise<OfferItem>;
      update(args?: any): Promise<OfferItem>;
      upsert(args?: any): Promise<OfferItem>;
      delete(args?: any): Promise<OfferItem>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    invoice: {
      findUnique(args?: any): Promise<Invoice | null>;
      findFirst(args?: any): Promise<Invoice | null>;
      findMany(args?: any): Promise<Invoice[]>;
      create(args?: any): Promise<Invoice>;
      update(args?: any): Promise<Invoice>;
      upsert(args?: any): Promise<Invoice>;
      delete(args?: any): Promise<Invoice>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    odeslaniFaktury: {
      findUnique(args?: any): Promise<OdeslaniFaktury | null>;
      findFirst(args?: any): Promise<OdeslaniFaktury | null>;
      findMany(args?: any): Promise<OdeslaniFaktury[]>;
      create(args?: any): Promise<OdeslaniFaktury>;
      update(args?: any): Promise<OdeslaniFaktury>;
      upsert(args?: any): Promise<OdeslaniFaktury>;
      delete(args?: any): Promise<OdeslaniFaktury>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    invoiceItem: {
      findUnique(args?: any): Promise<InvoiceItem | null>;
      findFirst(args?: any): Promise<InvoiceItem | null>;
      findMany(args?: any): Promise<InvoiceItem[]>;
      create(args?: any): Promise<InvoiceItem>;
      update(args?: any): Promise<InvoiceItem>;
      upsert(args?: any): Promise<InvoiceItem>;
      delete(args?: any): Promise<InvoiceItem>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    expenseCategory: {
      findUnique(args?: any): Promise<ExpenseCategory | null>;
      findFirst(args?: any): Promise<ExpenseCategory | null>;
      findMany(args?: any): Promise<ExpenseCategory[]>;
      create(args?: any): Promise<ExpenseCategory>;
      update(args?: any): Promise<ExpenseCategory>;
      upsert(args?: any): Promise<ExpenseCategory>;
      delete(args?: any): Promise<ExpenseCategory>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    expense: {
      findUnique(args?: any): Promise<Expense | null>;
      findFirst(args?: any): Promise<Expense | null>;
      findMany(args?: any): Promise<Expense[]>;
      create(args?: any): Promise<Expense>;
      update(args?: any): Promise<Expense>;
      upsert(args?: any): Promise<Expense>;
      delete(args?: any): Promise<Expense>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    postaStav: {
      findUnique(args?: any): Promise<PostaStav | null>;
      findFirst(args?: any): Promise<PostaStav | null>;
      findMany(args?: any): Promise<PostaStav[]>;
      create(args?: any): Promise<PostaStav>;
      update(args?: any): Promise<PostaStav>;
      upsert(args?: any): Promise<PostaStav>;
      delete(args?: any): Promise<PostaStav>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    columnLabel: {
      findUnique(args?: any): Promise<ColumnLabel | null>;
      findFirst(args?: any): Promise<ColumnLabel | null>;
      findMany(args?: any): Promise<ColumnLabel[]>;
      create(args?: any): Promise<ColumnLabel>;
      update(args?: any): Promise<ColumnLabel>;
      upsert(args?: any): Promise<ColumnLabel>;
      delete(args?: any): Promise<ColumnLabel>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    contractTemplate: {
      findUnique(args?: any): Promise<ContractTemplate | null>;
      findFirst(args?: any): Promise<ContractTemplate | null>;
      findMany(args?: any): Promise<ContractTemplate[]>;
      create(args?: any): Promise<ContractTemplate>;
      update(args?: any): Promise<ContractTemplate>;
      upsert(args?: any): Promise<ContractTemplate>;
      delete(args?: any): Promise<ContractTemplate>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    contract: {
      findUnique(args?: any): Promise<Contract | null>;
      findFirst(args?: any): Promise<Contract | null>;
      findMany(args?: any): Promise<Contract[]>;
      create(args?: any): Promise<Contract>;
      update(args?: any): Promise<Contract>;
      upsert(args?: any): Promise<Contract>;
      delete(args?: any): Promise<Contract>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    contractSignature: {
      findUnique(args?: any): Promise<ContractSignature | null>;
      findFirst(args?: any): Promise<ContractSignature | null>;
      findMany(args?: any): Promise<ContractSignature[]>;
      create(args?: any): Promise<ContractSignature>;
      update(args?: any): Promise<ContractSignature>;
      upsert(args?: any): Promise<ContractSignature>;
      delete(args?: any): Promise<ContractSignature>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    studio: {
      findUnique(args?: any): Promise<Studio | null>;
      findFirst(args?: any): Promise<Studio | null>;
      findMany(args?: any): Promise<Studio[]>;
      create(args?: any): Promise<Studio>;
      update(args?: any): Promise<Studio>;
      upsert(args?: any): Promise<Studio>;
      delete(args?: any): Promise<Studio>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    studioHours: {
      findUnique(args?: any): Promise<StudioHours | null>;
      findFirst(args?: any): Promise<StudioHours | null>;
      findMany(args?: any): Promise<StudioHours[]>;
      create(args?: any): Promise<StudioHours>;
      update(args?: any): Promise<StudioHours>;
      upsert(args?: any): Promise<StudioHours>;
      delete(args?: any): Promise<StudioHours>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    studioSlotPreset: {
      findUnique(args?: any): Promise<StudioSlotPreset | null>;
      findFirst(args?: any): Promise<StudioSlotPreset | null>;
      findMany(args?: any): Promise<StudioSlotPreset[]>;
      create(args?: any): Promise<StudioSlotPreset>;
      update(args?: any): Promise<StudioSlotPreset>;
      upsert(args?: any): Promise<StudioSlotPreset>;
      delete(args?: any): Promise<StudioSlotPreset>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    studioBlock: {
      findUnique(args?: any): Promise<StudioBlock | null>;
      findFirst(args?: any): Promise<StudioBlock | null>;
      findMany(args?: any): Promise<StudioBlock[]>;
      create(args?: any): Promise<StudioBlock>;
      update(args?: any): Promise<StudioBlock>;
      upsert(args?: any): Promise<StudioBlock>;
      delete(args?: any): Promise<StudioBlock>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    recordingRequest: {
      findUnique(args?: any): Promise<RecordingRequest | null>;
      findFirst(args?: any): Promise<RecordingRequest | null>;
      findMany(args?: any): Promise<RecordingRequest[]>;
      create(args?: any): Promise<RecordingRequest>;
      update(args?: any): Promise<RecordingRequest>;
      upsert(args?: any): Promise<RecordingRequest>;
      delete(args?: any): Promise<RecordingRequest>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    recordingSlot: {
      findUnique(args?: any): Promise<RecordingSlot | null>;
      findFirst(args?: any): Promise<RecordingSlot | null>;
      findMany(args?: any): Promise<RecordingSlot[]>;
      create(args?: any): Promise<RecordingSlot>;
      update(args?: any): Promise<RecordingSlot>;
      upsert(args?: any): Promise<RecordingSlot>;
      delete(args?: any): Promise<RecordingSlot>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    recordingEvent: {
      findUnique(args?: any): Promise<RecordingEvent | null>;
      findFirst(args?: any): Promise<RecordingEvent | null>;
      findMany(args?: any): Promise<RecordingEvent[]>;
      create(args?: any): Promise<RecordingEvent>;
      update(args?: any): Promise<RecordingEvent>;
      upsert(args?: any): Promise<RecordingEvent>;
      delete(args?: any): Promise<RecordingEvent>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    notification: {
      findUnique(args?: any): Promise<Notification | null>;
      findFirst(args?: any): Promise<Notification | null>;
      findMany(args?: any): Promise<Notification[]>;
      create(args?: any): Promise<Notification>;
      update(args?: any): Promise<Notification>;
      upsert(args?: any): Promise<Notification>;
      delete(args?: any): Promise<Notification>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    calendarFeed: {
      findUnique(args?: any): Promise<CalendarFeed | null>;
      findFirst(args?: any): Promise<CalendarFeed | null>;
      findMany(args?: any): Promise<CalendarFeed[]>;
      create(args?: any): Promise<CalendarFeed>;
      update(args?: any): Promise<CalendarFeed>;
      upsert(args?: any): Promise<CalendarFeed>;
      delete(args?: any): Promise<CalendarFeed>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    rodnyList: {
      findUnique(args?: any): Promise<RodnyList | null>;
      findFirst(args?: any): Promise<RodnyList | null>;
      findMany(args?: any): Promise<RodnyList[]>;
      create(args?: any): Promise<RodnyList>;
      update(args?: any): Promise<RodnyList>;
      upsert(args?: any): Promise<RodnyList>;
      delete(args?: any): Promise<RodnyList>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    caflouProjectsCache: {
      findUnique(args?: any): Promise<CaflouProjectsCache | null>;
      findFirst(args?: any): Promise<CaflouProjectsCache | null>;
      findMany(args?: any): Promise<CaflouProjectsCache[]>;
      create(args?: any): Promise<CaflouProjectsCache>;
      update(args?: any): Promise<CaflouProjectsCache>;
      upsert(args?: any): Promise<CaflouProjectsCache>;
      delete(args?: any): Promise<CaflouProjectsCache>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    preposlechChyba: {
      findUnique(args?: any): Promise<PreposlechChyba | null>;
      findFirst(args?: any): Promise<PreposlechChyba | null>;
      findMany(args?: any): Promise<PreposlechChyba[]>;
      create(args?: any): Promise<PreposlechChyba>;
      update(args?: any): Promise<PreposlechChyba>;
      upsert(args?: any): Promise<PreposlechChyba>;
      delete(args?: any): Promise<PreposlechChyba>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    preposlechStav: {
      findUnique(args?: any): Promise<PreposlechStav | null>;
      findFirst(args?: any): Promise<PreposlechStav | null>;
      findMany(args?: any): Promise<PreposlechStav[]>;
      create(args?: any): Promise<PreposlechStav>;
      update(args?: any): Promise<PreposlechStav>;
      upsert(args?: any): Promise<PreposlechStav>;
      delete(args?: any): Promise<PreposlechStav>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    preposlechStopa: {
      findUnique(args?: any): Promise<PreposlechStopa | null>;
      findFirst(args?: any): Promise<PreposlechStopa | null>;
      findMany(args?: any): Promise<PreposlechStopa[]>;
      create(args?: any): Promise<PreposlechStopa>;
      update(args?: any): Promise<PreposlechStopa>;
      upsert(args?: any): Promise<PreposlechStopa>;
      delete(args?: any): Promise<PreposlechStopa>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    preposlechOdkaz: {
      findUnique(args?: any): Promise<PreposlechOdkaz | null>;
      findFirst(args?: any): Promise<PreposlechOdkaz | null>;
      findMany(args?: any): Promise<PreposlechOdkaz[]>;
      create(args?: any): Promise<PreposlechOdkaz>;
      update(args?: any): Promise<PreposlechOdkaz>;
      upsert(args?: any): Promise<PreposlechOdkaz>;
      delete(args?: any): Promise<PreposlechOdkaz>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    herecDotocen: {
      findUnique(args?: any): Promise<HerecDotocen | null>;
      findFirst(args?: any): Promise<HerecDotocen | null>;
      findMany(args?: any): Promise<HerecDotocen[]>;
      create(args?: any): Promise<HerecDotocen>;
      update(args?: any): Promise<HerecDotocen>;
      upsert(args?: any): Promise<HerecDotocen>;
      delete(args?: any): Promise<HerecDotocen>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    vzorZpravy: {
      findUnique(args?: any): Promise<VzorZpravy | null>;
      findFirst(args?: any): Promise<VzorZpravy | null>;
      findMany(args?: any): Promise<VzorZpravy[]>;
      create(args?: any): Promise<VzorZpravy>;
      update(args?: any): Promise<VzorZpravy>;
      upsert(args?: any): Promise<VzorZpravy>;
      delete(args?: any): Promise<VzorZpravy>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    nastaveniOznameni: {
      findUnique(args?: any): Promise<NastaveniOznameni | null>;
      findFirst(args?: any): Promise<NastaveniOznameni | null>;
      findMany(args?: any): Promise<NastaveniOznameni[]>;
      create(args?: any): Promise<NastaveniOznameni>;
      update(args?: any): Promise<NastaveniOznameni>;
      upsert(args?: any): Promise<NastaveniOznameni>;
      delete(args?: any): Promise<NastaveniOznameni>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    mesicniPrehledOdeslan: {
      findUnique(args?: any): Promise<MesicniPrehledOdeslan | null>;
      findFirst(args?: any): Promise<MesicniPrehledOdeslan | null>;
      findMany(args?: any): Promise<MesicniPrehledOdeslan[]>;
      create(args?: any): Promise<MesicniPrehledOdeslan>;
      update(args?: any): Promise<MesicniPrehledOdeslan>;
      upsert(args?: any): Promise<MesicniPrehledOdeslan>;
      delete(args?: any): Promise<MesicniPrehledOdeslan>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    bonusZvukare: {
      findUnique(args?: any): Promise<BonusZvukare | null>;
      findFirst(args?: any): Promise<BonusZvukare | null>;
      findMany(args?: any): Promise<BonusZvukare[]>;
      create(args?: any): Promise<BonusZvukare>;
      update(args?: any): Promise<BonusZvukare>;
      upsert(args?: any): Promise<BonusZvukare>;
      delete(args?: any): Promise<BonusZvukare>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    projektNaklad: {
      findUnique(args?: any): Promise<ProjektNaklad | null>;
      findFirst(args?: any): Promise<ProjektNaklad | null>;
      findMany(args?: any): Promise<ProjektNaklad[]>;
      create(args?: any): Promise<ProjektNaklad>;
      update(args?: any): Promise<ProjektNaklad>;
      upsert(args?: any): Promise<ProjektNaklad>;
      delete(args?: any): Promise<ProjektNaklad>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    preposlechPozice: {
      findUnique(args?: any): Promise<PreposlechPozice | null>;
      findFirst(args?: any): Promise<PreposlechPozice | null>;
      findMany(args?: any): Promise<PreposlechPozice[]>;
      create(args?: any): Promise<PreposlechPozice>;
      update(args?: any): Promise<PreposlechPozice>;
      upsert(args?: any): Promise<PreposlechPozice>;
      delete(args?: any): Promise<PreposlechPozice>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    brunoNatoceno: {
      findUnique(args?: any): Promise<BrunoNatoceno | null>;
      findFirst(args?: any): Promise<BrunoNatoceno | null>;
      findMany(args?: any): Promise<BrunoNatoceno[]>;
      create(args?: any): Promise<BrunoNatoceno>;
      update(args?: any): Promise<BrunoNatoceno>;
      upsert(args?: any): Promise<BrunoNatoceno>;
      delete(args?: any): Promise<BrunoNatoceno>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    brunoPamet: {
      findUnique(args?: any): Promise<BrunoPamet | null>;
      findFirst(args?: any): Promise<BrunoPamet | null>;
      findMany(args?: any): Promise<BrunoPamet[]>;
      create(args?: any): Promise<BrunoPamet>;
      update(args?: any): Promise<BrunoPamet>;
      upsert(args?: any): Promise<BrunoPamet>;
      delete(args?: any): Promise<BrunoPamet>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    brunoPrirucka: {
      findUnique(args?: any): Promise<BrunoPrirucka | null>;
      findFirst(args?: any): Promise<BrunoPrirucka | null>;
      findMany(args?: any): Promise<BrunoPrirucka[]>;
      create(args?: any): Promise<BrunoPrirucka>;
      update(args?: any): Promise<BrunoPrirucka>;
      upsert(args?: any): Promise<BrunoPrirucka>;
      delete(args?: any): Promise<BrunoPrirucka>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    chatPise: {
      findUnique(args?: any): Promise<ChatPise | null>;
      findFirst(args?: any): Promise<ChatPise | null>;
      findMany(args?: any): Promise<ChatPise[]>;
      create(args?: any): Promise<ChatPise>;
      update(args?: any): Promise<ChatPise>;
      upsert(args?: any): Promise<ChatPise>;
      delete(args?: any): Promise<ChatPise>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    preposlechUdalost: {
      findUnique(args?: any): Promise<PreposlechUdalost | null>;
      findFirst(args?: any): Promise<PreposlechUdalost | null>;
      findMany(args?: any): Promise<PreposlechUdalost[]>;
      create(args?: any): Promise<PreposlechUdalost>;
      update(args?: any): Promise<PreposlechUdalost>;
      upsert(args?: any): Promise<PreposlechUdalost>;
      delete(args?: any): Promise<PreposlechUdalost>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    pripominkaPortalu: {
      findUnique(args?: any): Promise<PripominkaPortalu | null>;
      findFirst(args?: any): Promise<PripominkaPortalu | null>;
      findMany(args?: any): Promise<PripominkaPortalu[]>;
      create(args?: any): Promise<PripominkaPortalu>;
      update(args?: any): Promise<PripominkaPortalu>;
      upsert(args?: any): Promise<PripominkaPortalu>;
      delete(args?: any): Promise<PripominkaPortalu>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    pripominkaPriloha: {
      findUnique(args?: any): Promise<PripominkaPriloha | null>;
      findFirst(args?: any): Promise<PripominkaPriloha | null>;
      findMany(args?: any): Promise<PripominkaPriloha[]>;
      create(args?: any): Promise<PripominkaPriloha>;
      update(args?: any): Promise<PripominkaPriloha>;
      upsert(args?: any): Promise<PripominkaPriloha>;
      delete(args?: any): Promise<PripominkaPriloha>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    pozvankaUdaju: {
      findUnique(args?: any): Promise<PozvankaUdaju | null>;
      findFirst(args?: any): Promise<PozvankaUdaju | null>;
      findMany(args?: any): Promise<PozvankaUdaju[]>;
      create(args?: any): Promise<PozvankaUdaju>;
      update(args?: any): Promise<PozvankaUdaju>;
      upsert(args?: any): Promise<PozvankaUdaju>;
      delete(args?: any): Promise<PozvankaUdaju>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    navod: {
      findUnique(args?: any): Promise<Navod | null>;
      findFirst(args?: any): Promise<Navod | null>;
      findMany(args?: any): Promise<Navod[]>;
      create(args?: any): Promise<Navod>;
      update(args?: any): Promise<Navod>;
      upsert(args?: any): Promise<Navod>;
      delete(args?: any): Promise<Navod>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    bankConnection: {
      findUnique(args?: any): Promise<BankConnection | null>;
      findFirst(args?: any): Promise<BankConnection | null>;
      findMany(args?: any): Promise<BankConnection[]>;
      create(args?: any): Promise<BankConnection>;
      update(args?: any): Promise<BankConnection>;
      upsert(args?: any): Promise<BankConnection>;
      delete(args?: any): Promise<BankConnection>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    bankTransaction: {
      findUnique(args?: any): Promise<BankTransaction | null>;
      findFirst(args?: any): Promise<BankTransaction | null>;
      findMany(args?: any): Promise<BankTransaction[]>;
      create(args?: any): Promise<BankTransaction>;
      update(args?: any): Promise<BankTransaction>;
      upsert(args?: any): Promise<BankTransaction>;
      delete(args?: any): Promise<BankTransaction>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
    druhLicence: {
      findUnique(args?: any): Promise<DruhLicence | null>;
      findFirst(args?: any): Promise<DruhLicence | null>;
      findMany(args?: any): Promise<DruhLicence[]>;
      create(args?: any): Promise<DruhLicence>;
      update(args?: any): Promise<DruhLicence>;
      upsert(args?: any): Promise<DruhLicence>;
      delete(args?: any): Promise<DruhLicence>;
      deleteMany(args?: any): Promise<any>;
      createMany(args?: any): Promise<any>;
      updateMany(args?: any): Promise<any>;
      count(args?: any): Promise<number>;
      groupBy(args?: any): Promise<any[]>;
      aggregate(args?: any): Promise<any>;
    };
  }
  export namespace Prisma {
    type InputJsonValue = string | number | boolean | { [k: string]: InputJsonValue | null } | InputJsonValue[];
    type JsonValue = InputJsonValue | null;
    type TransactionClient = any;
    const JsonNull: any;
    const DbNull: any;
  }
}
